'use strict';
const KEY='chagog-v1', $=s=>document.querySelector(s);
const {schedule,migrate}=ReviewSchedule;
const day=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function plus(date,n){const [y,m,d]=date.split('-').map(Number);return day(new Date(y,m-1,d+n));}
let data={version:2,cards:[],history:[]}, storageOK=true;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);validateBackup(parsed);data=migrate(parsed);if(parsed.version===1){if(!localStorage.getItem(KEY+'-before-adaptive'))localStorage.setItem(KEY+'-before-adaptive',raw);localStorage.setItem(KEY,JSON.stringify(data));}}}catch(e){storageOK=false;notify('저장 데이터를 읽지 못했어요. 기존 데이터를 보호하기 위해 저장을 중지했어요.');}
function notify(t){$('#message').textContent=t;}
function commit(next){if(!storageOK){notify('저장소를 확인해야 합니다. 새로고침 후 다시 시도하세요.');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));data=next;return true;}catch(e){notify('저장 공간이 부족하거나 저장이 차단됐어요. 기록은 변경되지 않았습니다.');return false;}}
function elem(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function btn(text,fn,cls){const b=elem('button',text,cls);b.onclick=fn;return b;}
function validDay(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;return plus(s,0)===s;}
function validateContent(c){if(!c||typeof c!=='object'||['subject','question','answer'].some(k=>typeof c[k]!=='string'||!c[k].trim())||['explanation','source'].some(k=>c[k]!==undefined&&typeof c[k]!=='string'))throw Error('과목·질문·정답과 텍스트 형식을 확인하세요.');}
function validateBackup(v){if(![1,2].includes(v?.version)||!Array.isArray(v.cards)||!Array.isArray(v.history))throw Error('지원하지 않는 백업입니다.');const ids=new Set();for(const c of v.cards){validateContent(c);if(typeof c.id!=='string'||ids.has(c.id)||!validDay(c.created)||!(c.due===null||validDay(c.due))||(v.version===1?(!Number.isInteger(c.stage)||c.stage<0||c.stage>4):(!Number.isFinite(c.ease)||c.ease<1.3||c.ease>3||!Number.isInteger(c.interval)||c.interval<0||c.interval>365||!Number.isInteger(c.streak)||c.streak<0||c.due===null)))throw Error('카드 일정 또는 ID가 올바르지 않습니다.');if(c.retryAt!==undefined&&!Number.isFinite(Date.parse(c.retryAt)))throw Error('잘못된 재학습 시간');if(c.pendingAttempt!==undefined&&(!['remember','partial','none'].includes(c.pendingAttempt.recall)||!validDay(c.pendingAttempt.date)||!Number.isFinite(Date.parse(c.pendingAttempt.at))||typeof c.pendingAttempt.delayedFirst!=='boolean'))throw Error('잘못된 회상 기록');ids.add(c.id);}for(const h of v.history){if(typeof h.id!=='string'||typeof h.cardId!=='string'||!validDay(h.date)||!['correct','unsure','wrong'].includes(h.result))throw Error('복습 기록이 올바르지 않습니다.');}}
function newCard(c){validateContent(c);return {id:crypto.randomUUID(),subject:c.subject.trim(),question:c.question.trim(),answer:c.answer.trim(),explanation:c.explanation||'',source:c.source||'',verified:c.verified===true,created:day(),due:day(),ease:2.5,interval:0,streak:0};}
function render(){const today=day(), selected=$('#subjectFilter').value, subjects=[...new Set([...['국어','영어','한국사','컴퓨터일반','정보보호론'],...data.cards.map(c=>c.subject)])];const filter=$('#subjectFilter');filter.replaceChildren();const all=elem('option','전체 과목');all.value='';filter.append(all);for(const s of subjects){const o=elem('option',s);o.value=s;filter.append(o);}filter.value=subjects.includes(selected)?selected:'';const chosen=data.cards.filter(c=>!filter.value||c.subject===filter.value);$('#subjectCounts').textContent=subjects.filter(s=>data.cards.some(c=>c.subject===s)).map(s=>s+' '+ReviewLearning.queue(data.cards.filter(c=>c.subject===s)).length+'개 복습').join(' · ');const due=ReviewLearning.queue(chosen);const metric=ReviewLearning.metrics(chosen,data.history);$('#retention').textContent=metric.total?Math.round(100*metric.correct/metric.total)+'% ('+metric.correct+'/'+metric.total+')':'아직 기록 없음';const waiting=chosen.filter(c=>c.retryAt&&Date.parse(c.retryAt)>Date.now());$('#retryStatus').textContent=waiting.length?waiting.length+'개 재학습 대기 · 가장 빠른 재시도 '+new Date(Math.min(...waiting.map(c=>Date.parse(c.retryAt)))).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):'';$('#date').textContent=new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'short'});$('#due').textContent=due.length;$('#total').textContent=chosen.length;$('#done').textContent=data.history.filter(h=>h.date===today&&chosen.some(c=>c.id===h.cardId)).length;const root=$('#card');root.replaceChildren();const c=due[0];if(!c){root.append(elem('h2',waiting.length?'잠시 뒤 다시 떠올려 보세요':chosen.length?'오늘 복습을 마쳤어요':'첫 번째 카드를 남겨보세요'),elem('p',chosen.length?'저장된 카드 '+chosen.length+'개가 있어요. 복습 예정일이 되면 여기에 나타납니다.':data.cards.length?'선택한 과목에는 카드가 없어요. 전체 과목을 선택해 보세요.':'기본 카드를 준비하지 못했어요. 화면 아래 안내를 확인해 주세요.'));}else{root.append(elem('span',`${c.subject} · ${c.verified?'근거 확인':'근거 미확인'} · ${c.interval===0?'첫 학습':c.interval+'일 간격 복습'}`,'tag'),elem('div',c.question,'question'));if(c.pendingAttempt){renderAnswer(root,c);}else{const actions=elem('div',undefined,'actions');for(const [value,label] of [['remember','떠올렸어요'],['partial','일부만 떠올랐어요'],['none','모르겠어요']])actions.append(btn(label,()=>{const next=structuredClone(data);next.cards.find(x=>x.id===c.id).pendingAttempt=ReviewLearning.begin(c,data.history,value);if(commit(next))render();}));root.append(elem('p','정답을 열기 전에 기억에서 답해 보고 골라주세요.'),actions);}}}
function renderAnswer(root,c){const answer=elem('div',undefined,'answer');answer.append(elem('strong',c.answer),elem('p',c.explanation||'풀이 설명이 없습니다.'),elem('small',c.source?'출처: '+c.source:''));const actions=elem('div',undefined,'actions');for(const [value,label] of [['wrong','틀림 · 5분 뒤 다시'],['unsure','불완전 · 5분 뒤 다시'],['correct','맞힘']]){if(c.pendingAttempt.recall==='none'&&value!=='wrong')continue;if(c.pendingAttempt.recall==='partial'&&value==='correct')continue;actions.append(btn(label,()=>grade(c.id,value)));}root.append(answer,elem('p','방금 읽은 답의 익숙함이 아니라, 공개 전에 떠올린 답과 비교하세요.'),actions);}
function grade(id,result){const next=structuredClone(data),c=next.cards.find(x=>x.id===id);if(!c)return;try{const assessed=ReviewLearning.assess(c,data.history,result);next.cards[next.cards.findIndex(x=>x.id===id)]=assessed.card;next.history.push({id:crypto.randomUUID(),...assessed.entry});if(commit(next)){notify(result==='correct'?'복습 기록을 저장했어요.': '5분 뒤 다시 풀고, 다음 날에도 복습해요.');render();}}catch(e){notify('평가 실패: '+e.message);}}
$('#subjectFilter').onchange=render;
function installCorePack(automatic=false){try{const pack='core-2026-09-08-v1';if(automatic&&data.installedPacks?.includes(pack))return;const ids=new Set(data.cards.map(c=>c.id));const cards=CORE_REVIEW_PACK.filter(c=>!ids.has(c.id)).map(c=>({...newCard({...c,verified:true}),id:c.id}));if(commit({...data,cards:[...data.cards,...cards],installedPacks:[...new Set([...(Array.isArray(data.installedPacks)?data.installedPacks:[]),pack])]})){if(cards.length)notify(cards.length+'개 기출 복습 카드를 자동으로 준비했어요. 과목을 골라 바로 시작하세요.');if(!automatic)render();}}catch(e){notify('카드 준비 실패: '+e.message);}}
installCorePack(true);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});

setInterval(()=>{if(!document.hidden&&!$('#review').hidden&&!$('#card .question')&&ReviewLearning.queue(data.cards.filter(c=>!$('#subjectFilter').value||c.subject===$('#subjectFilter').value)).length)render();},15000);
