'use strict';
const KEY='chagog-v1', $=s=>document.querySelector(s);
const {schedule,migrate}=ReviewSchedule;
const day=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function plus(date,n){const [y,m,d]=date.split('-').map(Number);return day(new Date(y,m-1,d+n));}
let data={version:2,cards:[],history:[]}, storageOK=true;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);validateBackup(parsed);data=migrate(parsed);if(parsed.version===1){if(!localStorage.getItem(KEY+'-before-adaptive'))localStorage.setItem(KEY+'-before-adaptive',raw);localStorage.setItem(KEY,JSON.stringify(data));}}}catch(e){storageOK=false;notify('저장 데이터를 읽지 못했어요. 기존 데이터를 보호하기 위해 저장을 중지했어요.');}
function notify(t){$('#message').textContent=t;}
function commit(next){if(!storageOK){notify('저장소를 확인해야 합니다. 새로고침 후 다시 시도하세요.');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));data=next;return true;}catch(e){notify('저장 공간이 부족하거나 저장이 차단됐어요. 기록은 변경되지 않았습니다.');return false;}}
function elem(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function btn(text,fn,cls){const b=elem('button',text,cls);b.onclick=fn;return b;}
function validDay(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;return plus(s,0)===s;}
function validateContent(c){if(!c||typeof c!=='object'||['subject','question','answer'].some(k=>typeof c[k]!=='string'||!c[k].trim())||['explanation','source'].some(k=>c[k]!==undefined&&typeof c[k]!=='string'))throw Error('과목·질문·정답과 텍스트 형식을 확인하세요.');}
function validateBackup(v){if(![1,2].includes(v?.version)||!Array.isArray(v.cards)||!Array.isArray(v.history))throw Error('지원하지 않는 백업입니다.');const ids=new Set();for(const c of v.cards){validateContent(c);if(typeof c.id!=='string'||ids.has(c.id)||!validDay(c.created)||!(c.due===null||validDay(c.due))||(v.version===1?(!Number.isInteger(c.stage)||c.stage<0||c.stage>4):(!Number.isFinite(c.ease)||c.ease<1.3||c.ease>3||!Number.isInteger(c.interval)||c.interval<0||c.interval>365||!Number.isInteger(c.streak)||c.streak<0||c.due===null)))throw Error('카드 일정 또는 ID가 올바르지 않습니다.');if(c.retryAt!==undefined&&!Number.isFinite(Date.parse(c.retryAt)))throw Error('잘못된 재학습 시간');if(c.pendingAttempt!==undefined&&(!['remember','partial','none'].includes(c.pendingAttempt.recall)||!validDay(c.pendingAttempt.date)||!Number.isFinite(Date.parse(c.pendingAttempt.at))||typeof c.pendingAttempt.delayedFirst!=='boolean'))throw Error('잘못된 회상 기록');ids.add(c.id);}for(const h of v.history){if(typeof h.id!=='string'||typeof h.cardId!=='string'||!validDay(h.date)||!['correct','unsure','wrong'].includes(h.result))throw Error('복습 기록이 올바르지 않습니다.');}}
function newCard(c){validateContent(c);return {id:crypto.randomUUID(),subject:c.subject.trim(),question:c.question.trim(),answer:c.answer.trim(),explanation:c.explanation||'',source:c.source||'',verified:c.verified===true,created:day(),due:day(),ease:2.5,interval:0,streak:0};}
function render(){const today=day(), selected=$('#subjectFilter').value, subjects=[...new Set([...Array.from($('#form select').options,o=>o.value),...data.cards.map(c=>c.subject)])];const filter=$('#subjectFilter');filter.replaceChildren();const all=elem('option','전체 과목');all.value='';filter.append(all);for(const s of subjects){const o=elem('option',s);o.value=s;filter.append(o);}filter.value=subjects.includes(selected)?selected:'';const chosen=data.cards.filter(c=>!filter.value||c.subject===filter.value);$('#subjectCounts').textContent=subjects.filter(s=>data.cards.some(c=>c.subject===s)).map(s=>s+' '+ReviewLearning.queue(data.cards.filter(c=>c.subject===s)).length+'개 복습').join(' · ');const due=ReviewLearning.queue(chosen);const metric=ReviewLearning.metrics(chosen,data.history);$('#retention').textContent=metric.total?Math.round(100*metric.correct/metric.total)+'% ('+metric.correct+'/'+metric.total+')':'아직 기록 없음';const waiting=chosen.filter(c=>c.retryAt&&Date.parse(c.retryAt)>Date.now());$('#retryStatus').textContent=waiting.length?waiting.length+'개 재학습 대기 · 가장 빠른 재시도 '+new Date(Math.min(...waiting.map(c=>Date.parse(c.retryAt)))).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):'';$('#date').textContent=new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'short'});$('#due').textContent=due.length;$('#total').textContent=chosen.length;$('#done').textContent=data.history.filter(h=>h.date===today&&chosen.some(c=>c.id===h.cardId)).length;const root=$('#card');root.replaceChildren();const c=due[0];if(!c){root.append(elem('h2',waiting.length?'잠시 뒤 다시 떠올려 보세요':chosen.length?'오늘 복습을 마쳤어요':'첫 번째 카드를 남겨보세요'),elem('p','내용 추가에서 공부한 내용을 입력하거나 AI가 만든 문제를 가져올 수 있어요.'));}else{root.append(elem('span',`${c.subject} · ${c.verified?'근거 확인':'근거 미확인'} · ${c.interval===0?'첫 학습':c.interval+'일 간격 복습'}`,'tag'),elem('div',c.question,'question'));if(c.pendingAttempt){renderAnswer(root,c);}else{const actions=elem('div',undefined,'actions');for(const [value,label] of [['remember','떠올렸어요'],['partial','일부만 떠올랐어요'],['none','모르겠어요']])actions.append(btn(label,()=>{const next=structuredClone(data);next.cards.find(x=>x.id===c.id).pendingAttempt=ReviewLearning.begin(c,data.history,value);if(commit(next))render();}));root.append(elem('p','정답을 열기 전에 기억에서 답해 보고 골라주세요.'),actions);}}renderLibrary();}
function renderAnswer(root,c){const answer=elem('div',undefined,'answer');answer.append(elem('strong',c.answer),elem('p',c.explanation||'풀이 설명이 없습니다.'),elem('small',c.source?'출처: '+c.source:''));const actions=elem('div',undefined,'actions');for(const [value,label] of [['wrong','틀림 · 5분 뒤 다시'],['unsure','불완전 · 5분 뒤 다시'],['correct','맞힘']]){if(c.pendingAttempt.recall==='none'&&value!=='wrong')continue;if(c.pendingAttempt.recall==='partial'&&value==='correct')continue;actions.append(btn(label,()=>grade(c.id,value)));}root.append(answer,elem('p','방금 읽은 답의 익숙함이 아니라, 공개 전에 떠올린 답과 비교하세요.'),actions);}
function grade(id,result){const next=structuredClone(data),c=next.cards.find(x=>x.id===id);if(!c)return;try{const assessed=ReviewLearning.assess(c,data.history,result);next.cards[next.cards.findIndex(x=>x.id===id)]=assessed.card;next.history.push({id:crypto.randomUUID(),...assessed.entry});if(commit(next)){notify(result==='correct'?'복습 기록을 저장했어요.': '5분 뒤 다시 풀고, 다음 날에도 복습해요.');render();}}catch(e){notify('평가 실패: '+e.message);}}
function editCard(id){const c=data.cards.find(x=>x.id===id);if(!c)return;const next={...c,subject:prompt('과목',c.subject),question:prompt('질문',c.question),answer:prompt('정답',c.answer),explanation:prompt('이유·풀이',c.explanation),source:prompt('출처·쪽수',c.source)};try{validateContent(next);const n=structuredClone(data),target=n.cards.find(x=>x.id===id);Object.assign(target,next);delete target.pendingAttempt;if(commit(n)){notify('카드를 수정했어요.');render();}}catch(e){notify('수정 취소 또는 입력 오류: '+e.message);}}
function renderLibrary(){const q=$('#search').value.toLowerCase(),root=$('#list');root.replaceChildren();for(const c of data.cards.filter(c=>(!$('#subjectFilter').value||c.subject===$('#subjectFilter').value)&&[c.subject,c.question,c.source].join(' ').toLowerCase().includes(q))){const e=elem('div',undefined,'entry');e.append(elem('small',`${c.subject} · ${c.due?'다음 복습 '+c.due:'30일 복습 완료'}`),elem('h3',c.question),elem('p',c.answer));const a=elem('div',undefined,'actions');a.append(btn('편집',()=>editCard(c.id)),btn(c.verified?'근거 확인 취소':'근거 확인 표시',()=>{const n=structuredClone(data);n.cards.find(x=>x.id===c.id).verified=!c.verified;if(commit(n))render();}),btn('다시 학습',()=>{const n=structuredClone(data);delete n.cards.find(x=>x.id===c.id).pendingAttempt;delete n.cards.find(x=>x.id===c.id).retryAt;Object.assign(n.cards.find(x=>x.id===c.id),{created:day(),due:day(),ease:2.5,interval:0,streak:0});if(commit(n))render();}),btn('삭제',()=>{if(!confirm('이 카드와 복습 기록을 삭제할까요?'))return;const n=structuredClone(data);n.cards=n.cards.filter(x=>x.id!==c.id);n.history=n.history.filter(x=>x.cardId!==c.id);if(commit(n))render();}));e.append(a);root.append(e);}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{for(const name of ['review','add','library'])$('#'+name).hidden=name!==b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render();});
$('#form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);try{const c=newCard({...Object.fromEntries(f),verified:f.has('verified')});if(commit({...data,cards:[...data.cards,c]})){e.target.reset();notify('카드를 저장했어요. 오늘 복습에서 바로 풀 수 있어요.');render();}}catch(e){notify(e.message);}};
$('#importQuestions').onclick=()=>{try{const rows=JSON.parse($('#json').value);if(!Array.isArray(rows)||!rows.length||rows.length>500)throw Error('1~500개 문제의 JSON 배열을 넣어주세요.');const cards=rows.map(c=>newCard({...c,verified:false}));if(commit({...data,cards:[...data.cards,...cards]})){$('#json').value='';notify(`${cards.length}개 문제를 추가했어요. 정답 근거를 확인해주세요.`);render();}}catch(e){notify('가져오기 실패: '+e.message);}};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=elem('a');a.href=url;a.download=`chagog-${day()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#restore').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10000000)throw Error('10MB 이하 파일을 선택하세요.');const parsed=JSON.parse(await file.text());validateBackup(parsed);const incoming=migrate(parsed);const ids=new Set(data.cards.map(c=>c.id)),hids=new Set(data.history.map(h=>h.id));const fresh=incoming.cards.filter(c=>!ids.has(c.id));if(commit({...data,cards:[...data.cards,...fresh],history:[...data.history,...incoming.history.filter(h=>!hids.has(h.id))]})){notify(`${fresh.length}개 새 카드를 합쳤어요. 같은 ID의 기존 카드는 유지했습니다.`);render();}}catch(e){notify('백업 가져오기 실패: '+e.message);}finally{e.target.value='';}};
$('#subjectFilter').onchange=render;
$('#addCorePack').onclick=()=>{try{const ids=new Set(data.cards.map(c=>c.id));const cards=CORE_REVIEW_PACK.filter(c=>!ids.has(c.id)).map(c=>({...newCard({...c,verified:true}),id:c.id}));if(!cards.length){notify('이미 추가한 카드예요. 기존 복습 기록을 유지했어요.');return;}if(commit({...data,cards:[...data.cards,...cards]})){render();notify(cards.length+'개 기출 복습 카드를 추가했어요.');}}catch(e){notify('카드 추가 실패: '+e.message);}};
$('#search').oninput=renderLibrary;document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});

setInterval(()=>{if(!document.hidden&&!$('#review').hidden&&!$('#card .question')&&ReviewLearning.queue(data.cards.filter(c=>!$('#subjectFilter').value||c.subject===$('#subjectFilter').value)).length)render();},15000);
