// Curated practice, not verbatim exam questions. Variants can be written or multiple-choice.
(function(root){
 const bank={};
 function add(id,title,rule,hook,examples,rows){bank[id]={title,rule,hook,examples,variants:rows.map(([question,answer,explanation])=>({question,answers:Array.isArray(answer)?answer:[answer],explanation,type:'text'}))};}
 const id=k=>'en-session-20260909-'+k;
 add(id('wish'),'과거의 아쉬움','지금 과거의 일을 아쉬워하면 I wish + 주어 + had p.p.를 쓴다.','wish는 지금, had p.p.는 실제와 다른 과거',['I wish I had studied harder last year.'],[
 ['작년에 더 열심히 공부했더라면 좋을 텐데.\nI wish I ___ harder last year.\nstudy를 had + 과거분사 형태로 바꿔 빈칸에 쓸 말만 입력하세요.','had studied','과거 공부에 대한 아쉬움을 이번 문제에서 지정한 had + 과거분사로 쓰면 had studied다. 과거의 지속적인 공부를 아쉬워할 때는 had been studying도 가능하지만, 이 문제는 형태를 지정했다.'],
 ['이미 지나간 그 버스를 놓치지 않았더라면 좋을 텐데.\nI wish I ___ that bus.\nnot miss를 알맞은 형태로 바꿔 빈칸만 입력하세요.',['had not missed',"hadn't missed"],'과거 사실에 대한 아쉬움은 had not p.p.로 표현한다.']]);
 add(id('considering'),'considering의 연결 역할','considering + 문장은 “~라는 점을 고려하면”이다. considered에는 이 접속사 용법이 없다.','끝의 ing/ed가 아니라 단어의 용법 확인',['Considering the price, this laptop is good.'],[
 ['“비가 온 것을 감안하면”이라는 뜻이 되도록 [considered]만 고쳐 쓰세요.\n[Considered] it was raining, many people came.','considering','considering이 “~라는 점을 고려하면”이라는 연결 역할을 한다.'],
 ['“가격을 감안하면”이라는 뜻이 되도록 빈칸에 considering 또는 considered 중 하나를 직접 쓰세요.\n___ the price, this laptop is good.','considering','considering은 명사구 the price 앞에서도 “~을 고려하면”이라는 뜻으로 쓴다.']]);
 add(id('while'),'while과 during','during 뒤에는 기간·사건 명사구, while 뒤에는 보통 절이 온다. while studying 같은 축약도 가능하다.','시간 덩어리 during / 일이 벌어지는 절 while',['during the meeting / while we were meeting'],[
 ['while 또는 during 중 하나를 직접 쓰세요.\nPlease remain quiet ___ the concert.','during','the concert는 명사구이므로 during을 쓴다.'],
 ['while 또는 during 중 하나를 직접 쓰세요.\nI took notes ___ the teacher was speaking.','while','the teacher was speaking은 주어와 동사가 있는 절이다.']]);
 add(id('comparative'),'~할수록 더','the + 비교급 ..., the + 비교급 ...으로 두 변화를 연결한다.','더 빨라질수록 → 더 일찍',['The faster you walk, the sooner you arrive.'],[
 ['“더 빨리 걸을수록 더 일찍 도착한다.”\nThe ___ you walk, the sooner you arrive.\nfast를 알맞게 바꿔 빈칸만 쓰세요.','faster','the faster ..., the sooner ...로 비교급을 대응시킨다.'],
 ['“더 오래 기다릴수록 더 불안해진다.”\nThe longer I wait, ___ more nervous I become.\n빠진 한 단어를 쓰세요.','the','두 번째 비교급 앞에도 the가 필요하다.']]);
 add(id('no-means'),'by no means','by no means 자체가 “결코 ~아니다”라는 부정 표현이다.','no에 부정 의미가 들어 있다',['The task is by no means easy.'],[
 ['“그 일은 결코 쉽지 않다.”\nThe task is by ___ means easy.\n빠진 한 단어를 쓰세요.','no','by no means = 결코 ~아니다.'],
 ['“그녀는 결코 게으르지 않다.”\nShe is by no ___ lazy.\n빠진 한 단어를 쓰세요.','means','by no means라는 표현으로 익힌다.']]);
 add(id('poor-as'),'형용사 + as의 양보','형용사 + as + 주어 + 동사는 “비록 ~하지만”이라는 뜻으로 쓸 수 있다.','형용사를 앞세워 “그렇기는 하지만”',['Tired as he was, he finished the work.'],[
 ['“비록 피곤했지만 그는 일을 마쳤다.”\nTired ___ he was, he finished the work.\nas 또는 because 중 하나를 쓰세요.','as','Tired as he was는 Although he was tired와 같은 양보 의미다.'],
 ['“비록 어리지만 그녀는 현명하다.”\n___ as she is, she is wise.\nyoung 또는 youth 중 하나를 쓰세요.','young','형용사 young을 앞에 놓는 양보 구문이다.']]);
 add(id('as-well'),'A 중심에 B 덧붙이기','격식 문법에서 주어가 A as well as B이면, 덧붙인 B를 잠깐 빼고 A의 인칭과 수에 동사를 맞춘다. 쉼표 유무만으로 and와 같은 수일치 규칙으로 바꾸지 않는다. 현재 be동사는 I에 am, you에 are, 3인칭 단수에 is, 복수에 are를 쓴다. 한 사람을 가리키는 you도 are다.','B를 괄호로 빼고 A의 인칭과 수 확인',['The teacher, as well as the students, is ready.','The teacher as well as the students is ready.','The students, as well as the teacher, are ready.','You, as well as he, are responsible.','I, as well as she, am ready.'],[
 ['격식 문법 기준으로 현재 상태를 나타내는 빈칸에 is 또는 are를 쓰세요.\nThe students, as well as their teacher, ___ ready.','are','teacher는 덧붙인 말이다. 잠깐 지우면 The students are ready가 남는다. students가 여럿이므로 are다.'],
 ['격식 문법 기준으로 [are]만 고쳐 쓰세요.\nThe teacher, as well as the students, [are] ready.','is','덧붙인 as well as the students를 빼면 The teacher is ready가 남는다.']]);
 add(id('adverb'),'형용사를 꾸미는 부사','형용사를 “어느 정도로”라고 꾸미려면 부사를 쓴다.','놀라운 결과 / 놀라울 정도로 긴',['a surprising result / a surprisingly long trip'],[
 ['[surprising]만 고쳐 쓰세요.\nThe trip was [surprising] long.','surprisingly','형용사 long을 꾸미는 부사 surprisingly가 필요하다.'],
 ['[extreme]만 고쳐 쓰세요.\nThe water is [extreme] cold.','extremely','형용사 cold를 꾸미는 부사는 extremely다.']]);
 add(id('neither'),'가까운 쪽에 맞추는 주어','either A or B는 둘 중 하나, neither A nor B는 둘 다 아니라는 뜻이다. 주어를 연결하는 이 예문들에서는 동사에 가까운 B에 맞춘다. not only A but also B도 여기서는 가까운 B에 맞추지만, 뜻은 A뿐 아니라 B도라는 강조다. B가 더 중요해서 동사를 맞추는 것은 아니다.','뜻과 동사 일치 기준은 구별',['Neither the teacher nor the students are ready.','Neither the teachers nor the student is ready.','Either the secretary or the managers are available.','Not only the teacher but also the students are ready.'],[
 ['격식 문법의 수일치 기준으로 is 또는 are를 쓰세요.\nNeither the manager nor the workers ___ ready.','are','동사 바로 앞의 workers는 여러 명이다. neither … nor 구문에서는 가까운 쪽에 맞추므로 are다.'],
 ['격식 문법의 수일치 기준으로 [are]만 고쳐 쓰세요.\nNeither the workers nor the manager [are] ready.','is','판별 연습용 예문이다. 가까운 manager가 단수이므로 is다. 직접 쓸 때는 복수 주어를 뒤에 두면 더 매끄럽다.']]);
 add(id('rage'),'진행형과 수동태','rage는 여기서 주어 자체가 맹렬하게 벌어지거나 몰아친다는 자동사다.','폭풍 자체가 몰아친다',['The storm has been raging all night.','People have discussed the issue. → The issue has been discussed.'],[
 ['현재완료진행형 문장이 되도록 [raged]만 고쳐 쓰세요.\nThe storm has been [raged] all night.','raging','폭풍이 몰아치는 것이므로 진행형 raging이다. rage의 이 의미는 수동태로 쓰지 않는다.'],
 ['“그 사안은 여러 번 논의되어 왔다.”\nThe issue has been ___ many times.\ndiscuss를 알맞게 바꿔 빈칸만 쓰세요.','discussed','사람들이 사안을 논의한다는 능동문이 가능하다. 사안은 논의되는 대상이므로 수동형 discussed다.']]);
 add(id('time-clause'),'미래 시간절의 현재·현재완료','미래의 때를 정하는 시간 부사절에서는 단순한 미래 예측의 will 대신 단순현재를 쓴다. 동작이 완료된 뒤임을 강조하면 현재완료도 가능하다. 모든 when절에 적용하는 규칙은 아니다.','때를 정하는 절: arrives / 완료를 강조: has arrived',['When she arrives, we will leave.','When she has arrived, we will leave.','I do not know when she will arrive. → 언제 도착할지 모른다는 내용의 명사절이므로 will을 쓸 수 있다.'],[
 ['[will arrive]를 arrive의 단순현재 또는 현재완료 형태로 고쳐 쓰세요.\nWhen she [will arrive], we will leave.',['arrives','has arrived'],'arrives와 has arrived 모두 가능하다. has arrived는 도착이 완료된 다음 출발한다는 점을 강조한다. 미래의 때를 정하는 이 부사절에서는 단순한 미래 예측의 will arrive를 쓰지 않는다.'],
 ['“비가 그칠 때까지 기다릴게.”\nI will wait until the rain ___.\nstop의 단순현재 또는 현재완료 형태로 빈칸만 쓰세요.',['stops','has stopped'],'stops와 has stopped 모두 가능하다. has stopped는 비가 그친 상태에 도달함을 강조한다. until 뒤라고 현재완료가 금지되는 것은 아니다.']]);
 add(id('knowledge'),'긴 설명 속 중심 주어','뒤에 붙은 설명을 잠깐 지우고, 무엇에 대한 문장인지 본다. 문들에 대한 열쇠라면 주어는 열쇠다. some of처럼 일부를 뜻하는 표현은 따로 본다.','문들이 아니라 열쇠 하나',['The key to the front doors is missing.'],[
 ['is 또는 are를 쓰세요.\nThe key to the front doors ___ missing.','is','front doors는 어떤 문에 쓰는 열쇠인지 설명한다. 진짜 주어는 key 하나이므로 is다.'],
 ['[are]만 고쳐 쓰세요.\nKnowledge of these rules [are] useful.','is','중심 주어 knowledge는 불가산명사이므로 단수 동사를 쓴다.']]);
 add(id('help'),'help 뒤의 동사','help + 목적어 뒤에는 동사원형과 to부정사가 모두 가능하다.','help는 두 형태 허용',['This course helps students learn English.','This course helps students to learn English.'],[
 ['[learning]을 동사원형 또는 to부정사로 고쳐 쓰세요.\nThis course helps students [learning] English.',['learn','to learn'],'help students learn과 help students to learn 모두 가능하다.'],
 ['[becoming]을 동사원형 또는 to부정사로 고쳐 쓰세요.\nPractice helps me [becoming] confident.',['become','to become'],'help me become과 help me to become을 모두 정답으로 인정한다.']]);
 add(id('difficulty'),'have difficulty (in) -ing','have difficulty 뒤에는 in을 넣거나 생략하고 -ing를 쓸 수 있다.','in이 없어도 연결되는 표현',['I have difficulty remembering names.','I have difficulty in remembering names.'],[
 ['[remember]만 고쳐 쓰세요.\nI have difficulty in [remember] names.','remembering','in 뒤에 remembering을 쓴다. in은 생략할 수도 있다.'],
 ['[understand]를 -ing형으로 고쳐 쓰세요. 이 표현에서 선택적인 전치사 in은 함께 써도 됩니다.\nShe has difficulty [understand] the rule.',['understanding','in understanding'],'have difficulty understanding과 have difficulty in understanding 모두 가능하다. in을 넣거나 생략할 수 있다는 규칙을 채점에도 똑같이 적용한다.']]);
 add(id('used-to'),'get used to -ing','get used to의 to는 전치사다. 명사 또는 -ing가 뒤따른다.','~하는 생활에 익숙해지기',['I got used to working at night.'],[
 ['동사 [answer]를 -ing형으로 고쳐 쓰세요.\nI got used to [answer] calls at night.','answering','answer calls는 전화를 받는다는 뜻이다. get used to의 to는 전치사이므로 뒤의 동사 answer를 answering으로 바꾼다.'],
 ['[live]만 고쳐 쓰세요.\nShe is getting used to [live] alone.','living','get used to 뒤에 living을 쓴다.']]);
 add(id('both-whom'),'them을 관계절로 연결','별도 문장에서는 both of them, 앞의 사람을 받는 관계절에서는 both of whom을 쓴다.','of them의 목적격 → of whom의 목적격',['I have two sisters. Both of them are doctors.','I have two sisters, both of whom are doctors.'],[
 ['[them]만 관계대명사로 고쳐 쓰세요.\nI have two sisters, both of [them] are doctors.','whom','콤마 뒤를 앞의 sisters에 연결하는 관계절로 만들려면 whom을 쓴다.'],
 ['두 개의 독립된 문장입니다. them 또는 whom 중 하나를 쓰세요.\nI have two sisters. Both of ___ are doctors.','them','마침표로 나눈 별도 문장이므로 Both of them이다.']]);
 add(id('all-whom'),'전체 역할과 내부 역할','all of whom were kind에서는 all of whom 전체가 were의 주어이고, 그 안의 whom은 전치사 of의 목적어다. all of whom I liked에서는 I가 주어이고 all of whom은 liked의 목적어다. 전체의 역할은 뒤 절의 구조를 보고 판단한다.','of 뒤의 whom / 전체 역할은 문장에 따라',['I met three teachers, all of whom were kind. → 전체가 were의 주어','I met three teachers, all of whom I liked. → 전체가 liked의 목적어'],[
 ['who 또는 whom 중 하나를 쓰세요.\nI met three teachers, all of ___ were kind.','whom','of 뒤의 목적격이므로 whom이다. all of whom 전체는 were의 주어다.'],
 ['who 또는 whom 중 하나를 쓰세요.\nI met three teachers ___ were kind.','who','이번에는 전치사 of가 없고 관계대명사 자체가 were의 주어이므로 who다.']]);
 add(id('provided'),'provided의 조건','provided (that)과 providing (that)은 조건을 나타낼 수 있다. -ed라는 끝모양만 보고 접속사인지 판단하지 않는다.','조건이 충족되면 가능',['You may borrow my pen provided that you return it.'],[
 ['“비밀로 한다는 조건으로 알려 줄게.”\nI will tell you ___ that you keep it secret.\nprovided 또는 considered 중 하나를 쓰세요.','provided','provided that은 조건을 나타낸다. considered that에는 이 접속사 용법이 없다.'],
 ['“조용히 한다는 조건으로 여기 있어도 돼.”\nYou can stay here ___ you keep quiet.\nprovided를 사용해 빈칸을 쓰세요. that은 넣거나 생략해도 됩니다.',['provided','provided that'],'provided 뒤의 that은 생략할 수 있다. 주절은 머물러도 된다는 허용, 뒤 절은 그 조건이다.']]);
 add(id('while-short'),'while절 줄이기','while절과 주절의 주어가 같고 while절에 be동사가 있을 때, 이 예문들에서는 주어와 be동사를 함께 생략할 수 있다. -ing 행동의 주인이 주절 주어인지 확인한다.','누가 행동하는지 같아야 한다',['While she was cooking, she listened to the radio. → While cooking, she listened to the radio.'],[
 ['While I was waiting for the bus, I read the notice.\n같은 뜻이 되도록 줄인 문장의 빈칸을 wait의 -ing형으로 채우세요.\nWhile ___ for the bus, I read the notice.','waiting','기다린 사람과 안내문을 읽은 사람이 모두 I다. I was를 함께 빼고 waiting을 남긴다.'],
 ['While she was checking the file, she noticed an error.\n주어와 be동사를 생략한 문장에서 check의 -ing형을 쓰세요.\nWhile ___ the file, she noticed an error.','checking','확인한 사람과 오류를 알아챈 사람이 she로 같다. While checking the file로 줄일 수 있다.']]);
 add(id('nothing'),'nothing과 원급 비교','Nothing is as ... as X는 X만큼 ...한 것이 없다는 뜻이다. everything으로 바꾸면 모든 것이 X만큼 그렇다는 뜻으로 달라진다.','아무것도 그만큼은 아니다',['Nothing is as valuable as trust.'],[
 ['“이보다 더 중요한 것은 없다.”\n___ is more important than this.\nNothing 또는 Everything 중 하나를 쓰세요.','nothing','Nothing이 더 중요한 것이 하나도 없다는 부정을 만든다.'],
 ['“그 여행에서 집만큼 편안한 곳은 없었다.”\nOn that trip, nowhere was as comfortable ___ home.\n원급 비교를 완성하는 한 단어를 쓰세요.','as','as + 형용사 + as로 같은 정도를 비교한다. nowhere와 결합하여 집만큼 편안한 곳이 없었다는 뜻이다.']]);
 add(id('debate-head'),'관계절의 주인 찾기','관계절의 동작을 누가 하거나 어떤 것이 겪는지 확인한다. 후보 명사를 관계절의 주어 자리에 넣어 뜻과 구조를 비교한 뒤, 가리키는 명사에 동사를 맞춘다. 가장 가까운 명사나 주절의 중심 명사라고 무조건 고르지 않는다.','후보를 넣어 읽기 → 뜻 확인 → 수일치',['The discussion of the plans that has lasted all day is still unresolved. → 하루 종일 이어진 것은 논의','The files in the box that contain the data are encrypted. → 데이터를 담는 것은 파일들'],[
 ['데이터를 담고 있는 것은 상자가 아니라 여러 파일이다.\nThe files in the box that ___ the data are encrypted.\ncontain 또는 contains 중 하나를 쓰세요.','contain','관계절에 후보를 넣으면 the files contain the data가 이 문맥에 맞는다. files가 복수이므로 contain이다. 가까운 box에 끌려가 contains를 고르지 않는다.'],
 ['작년에 개관한 것은 방이 아니라 박물관이다.\nThe rooms in the museum that ___ opened last year are spacious.\nwas 또는 were 중 하나를 쓰세요.','was','관계절의 주어로 the museum을 넣으면 박물관이 작년에 개관했다는 뜻이 된다. museum은 단수이므로 was다. 이 예문에서는 가까운 명사가 선행사다.']]);
 add('core-en-2026national-3','요구절의 동사원형','요구의 의미로 쓰인 require 등의 that절에서는 주어의 수와 상관없이 동사원형을 쓸 수 있다. and로 병렬인 동사도 같은 구조로 맞춘다. 모든 that절의 규칙은 아니다.','요구한 행동들을 같은 형태로',['The rule requires that each visitor show an ID and sign the form.'],[
 ['요구를 나타내는 that절에서 [attends]를 앞의 read와 병렬이 되도록 한 단어로 고치세요.\nThe director requests that every member read the report and [attends] the meeting.','attend','read와 attend가 요구된 행동으로 나란히 연결됐다. 주어 every member가 단수여도 이 구문에서는 동사원형이다.'],
 ['다음 that절은 요구를 나타내며, 앞의 check와 같은 동사 형태를 써야 합니다.\nThe policy requires that every clerk check the date and [records] the number.\n[records]만 고쳐 쓰세요.','record','check와 record를 병렬로 쓴다. requires의 -s를 that절 안의 record에 옮기지 않는다.']]);
 add('core-en-2026national-13','관계절의 빈자리','장소 명사 뒤라도 관계절에 주어가 없으면 which나 that 같은 관계대명사를 쓴다. where는 장소를 나타내며 주어 역할을 대신하지 않는다.','장소라는 뜻보다 뒤 절의 빈자리',['This is a town that attracts many visitors.','This is the town where my aunt lives.'],[
 ['which 또는 where 중 하나를 쓰세요.\nWe visited an island ___ attracts many tourists.','which','attracts의 주어가 비어 있다. which가 island를 받아 주어가 된다. where는 이 주어 자리를 채우지 못한다.'],
 ['which 또는 where 중 하나를 쓰세요.\nThis is the village ___ my grandparents live.','where','my grandparents가 주어, live가 동사로 이미 있다. 빈칸은 사는 장소를 연결하므로 where다.']]);
 add('core-en-2026national-14','to부정사의 능동·수동','주어가 부정사 동작을 하는지 받는지 확인한다. 해결되는 문제, 수리되는 장치는 수동 부정사 to be + 과거분사로 쓴다.','누가 고치고 무엇이 고쳐지는가',['The device is expected to be repaired tomorrow.'],[
 ['“그 장치는 내일 수리될 것으로 예상된다.”\nThe device is expected ___ tomorrow.\nrepair를 사용하여 수동형 to부정사를 쓰세요.','to be repaired','장치는 수리되는 대상이다. to be repaired가 수동형 to부정사다.'],
 ['“이 보고서는 금요일까지 완성될 것이다.”라는 예상을 나타낸다.\nThe report is expected [to finish] by Friday.\nfinish를 사용해 대괄호 부분을 수동형 to부정사로 고치세요.','to be finished','보고서는 완성되는 대상이므로 to be finished다. expected 자체가 수동형이어도 뒤 부정사의 태를 따로 확인한다.']]);
 const extra=(key,title,rule,hook,examples,rows)=>add('grammar-agreement-'+key,title,rule,hook,examples,rows);
 extra('each','each의 위치','Each of the students는 학생들 중 각 한 명을 가리킨다. The students each는 학생들이 주어이고 each가 뒤에 붙는다. each/every가 각각의 단수 명사에 붙은 each A and each B, every A and every B도 단수로 쓴다.','각 한 명 / 학생들이 각각',['Each of them has a book.','They each have a book.','Every driver and every passenger has a ticket.'],[
 ['has 또는 have를 쓰세요.\nEach of the students ___ a book.','has','학생들 중 각 한 명을 가리키는 each가 주어다. 단수이므로 has다.'],['has 또는 have를 쓰세요.\nThe students each ___ a book.','have','이번에는 students가 주어이고 each는 뒤에 붙었다. 학생들이 여럿이므로 have다.'],['[have]만 고쳐 쓰세요.\nEach of them [have] a ticket.','has','each of them에서 중심은 단수 each다.']]);
 extra('number','여러 학생과 학생 수','a number of는 “여러”, the number of는 “~의 수”이다.','학생들 / 숫자 하나',['A number of students are absent.','The number of students is increasing.'],[
 ['is 또는 are를 쓰세요.\nThe number of visitors ___ increasing.','is','방문객 수라는 숫자 하나를 말하므로 is다.'],['is 또는 are를 쓰세요.\nA number of visitors ___ waiting outside.','are','여러 방문객을 뜻하므로 are다.'],['[are]만 고쳐 쓰세요.\nThe number of books [are] increasing.','is','책들이 아니라 책의 수가 주어다.']]);
 extra('portion','무엇의 일부인가','some of는 일부, half of는 절반이다. all of와 most of도 무엇을 가리키는지 of 뒤의 대상 명사를 본다. 물은 불가산이라 is, 학생들은 복수라 are에 맞춘다.','물 일부 / 학생 일부',['Some of the water is dirty.','Some of the students are absent.','Most of the furniture is old.','All of the chairs are broken.'],[
 ['is 또는 are를 쓰세요.\nHalf of the water ___ gone.','is','water는 불가산명사이므로 is다.'],['is 또는 are를 쓰세요.\nHalf of the students ___ here.','are','students는 복수이므로 are다.'],['[are]만 고쳐 쓰세요.\nSome of the equipment [are] broken.','is','equipment는 불가산명사이므로 is다.']]);
 extra('pair','scissors와 pair','가위 한 개여도 scissors라고 쓰고 are를 붙인다. a pair of scissors에서는 pair가 주어의 중심이므로 is다. 실제 가위 개수가 달라진 것은 아니다.','실제 개수보다 중심 명사의 형태',['These scissors are sharp.','This pair of scissors is sharp.'],[
 ['is 또는 are를 쓰세요.\nThis pair of scissors ___ sharp.','is','중심 명사 pair가 단수다.'],['is 또는 are를 쓰세요.\nThese scissors ___ sharp.','are','scissors는 복수형으로 취급한다. 실제 가위가 한 개여도 같다.'],['is 또는 are를 쓰세요.\nTwo pairs of scissors ___ on the desk.','are','중심 명사 pairs가 복수다.']]);
 extra('identity','역할 둘과 사람 둘','친구이자 동료인 한 명인지, 친구와 동료 두 명인지 앞 문장부터 읽는다. 한 명이라고 적혀 있으면 is, 두 명이면 are다.','역할의 개수와 사람의 개수는 다르다',['민호 한 명이 친구이면서 동료다: My friend and colleague is here.','친구 민호와 동료 지수 두 명이다: My friend and my colleague are here.'],[
 ['방문자는 민호 한 명뿐이다. 민호는 내 친구이면서 동료다.\nMy friend and colleague ___ here.\nis 또는 are를 쓰세요.','is','앞 문장이 민호 한 명뿐이라고 알려 줬다. 친구와 동료는 그 한 사람의 역할이므로 is다.'],['방문자는 친구 민호와 동료 지수, 두 명이다.\nMy friend and my colleague ___ here.\nis 또는 are를 쓰세요.','are','서로 다른 두 사람을 함께 주어로 묶었으므로 are다.'],['내 남자 형제와 여자 형제가 각각 한 명씩 와 있다.\nMy brother and sister ___ here.\nis 또는 are를 쓰세요.','are','my를 한 번만 썼어도 문맥상 두 사람이므로 복수다.']]);
 extra('together','함께 온 사람은 덧붙임','together with나 along with 뒤의 B는 함께 온 사람이나 물건을 덧붙인 말이다. 그 부분을 지우고 앞의 A에 동사를 맞춘다.','동행자가 늘어도 중심은 A',['The teacher, together with the students, is here.'],[
 ['is 또는 are를 쓰세요.\nThe teacher, together with the students, ___ here.','is','학생들은 함께 온 사람들이다. 진짜 주어는 teacher 한 명이므로 is다.'],['is 또는 are를 쓰세요.\nThe players, including their captain, ___ ready.','are','including their captain은 주장이 포함된다는 설명이다. 진짜 주어 players는 여러 명이므로 are다.'],['[are]만 고쳐 쓰세요.\nThe box, along with the bags, [are] missing.','is','중심 주어 box가 단수다.']]);
 extra('existential','뒤에 놓인 주어','there is/are와 장소 도치에서는 동사 뒤에 나오는 주어의 수를 확인한다. 구어의 there’s + 복수 용례와 격식 문법 문제의 기준을 구별한다. There + A and B처럼 단복수가 섞인 목록은 이번 앱에서 단일 정답 문제로 출제하지 않는다. 실제 기출은 제시된 문맥과 기준에 따라 판단한다.','장소가 아니라 존재하는 대상',['There are two chairs by the window.','On the shelf is a small clock.','There is a notebook, and there are two pens. → 절을 나누어 일치를 분명하게 쓴 대안'],[
 ['격식 문법 기준으로 is 또는 are를 쓰세요.\nThere ___ several messages in the inbox.','are','존재하는 대상은 여러 messages다. 복수에 맞춰 are를 쓴다.'],
 ['is 또는 are를 쓰세요.\nOn the wall ___ a large map.','is','On the wall은 장소이고 실제 주어는 뒤의 a large map이다. 지도 하나이므로 is다.']]);
 extra('collective','팀 하나와 팀원들','team, audience 같은 집합명사는 하나의 집단으로 보면 단수로, 구성원을 떠올리는 영국식 용례에서는 복수로도 쓴다. members처럼 복수 명사가 명시된 경우와 구별한다.','집합명사는 문맥·사용역 확인',['The team is ready. → 팀을 하나로 보는 단수 일치','The team members are ready. → 주어가 복수 members'],[
 ['is 또는 are를 쓰세요.\nThe committee members ___ discussing the proposal.','are','중심 명사는 복수 members다. committee가 단수형으로 보인다는 이유로 is를 쓰지 않는다.'],
 ['영국식 영어를 포함하여 가능한 형태 하나를 is 또는 are 중에서 쓰세요.\nThe audience ___ waiting quietly.',['is','are'],'audience를 하나의 집단으로 보면 is, 구성원들을 떠올리는 영국식 용례에서는 are도 가능하다. 이 문제는 두 형태를 모두 인정한다.']]);
 extra('noun-form','s와 실제 문법상 수','news와 학문명 mathematics는 s로 끝나도 단수다. information과 equipment는 불가산명사다. 일반적으로 경찰들을 뜻하는 the police는 복수로 쓴다.','철자 s만 보고 세지 않기',['The news is encouraging.','The police are investigating.'],[
 ['is 또는 are를 쓰세요.\nThe information on these pages ___ accurate.','is','주어 information은 불가산명사다. pages가 복수여도 정보 자체에 맞춰 is다.'],
 ['학문 이름으로 사용한 mathematics입니다. is 또는 are를 쓰세요.\nMathematics ___ my favorite subject.','is','학문 한 분야를 나타내는 mathematics는 단수로 취급한다.'],
 ['경찰관들을 가리키는 일반적인 용법입니다. is 또는 are를 쓰세요.\nThe police ___ searching for the missing child.','are','이 뜻의 police는 복수로 취급한다. s가 없다고 단수로 판단하지 않는다.'],
 ['is 또는 are를 쓰세요.\nThe news about the rescue ___ encouraging.','is','news는 복수형처럼 보여도 단수 동사를 쓴다.']]);
 extra('one','one을 중심으로 읽기','one of + 복수명사는 여럿 중 하나를 가리킨다. more than one + 단수명사는 의미가 여럿이어도 보통 단수 동사를 쓴다.','여럿 중 하나 / 뜻은 여럿이어도 one',['One of the tickets is missing.','More than one applicant has called.'],[
 ['is 또는 are를 쓰세요.\nOne of the windows ___ open.','is','창문들 중 하나가 주어다. windows의 복수형에 끌려가지 않고 one에 맞춘다.'],
 ['일반적인 격식 문법 기준으로 has 또는 have를 쓰세요.\nMore than one employee ___ asked for a copy.','has','more than one + 단수명사 employee의 보통 일치는 단수 has다. 뜻이 두 명 이상이라는 이유만으로 have로 바꾸지 않는다.']]);
 extra('amount','총액 하나와 지폐 여러 장','돈·시간·거리 등을 하나의 총량으로 말할 때는 단수 동사를 쓴다. 지폐처럼 개별 물건을 세는 복수 명사와 구분한다.','총액 / 낱장',['Twenty dollars is enough for lunch.','Twenty one-dollar bills are in the envelope.'],[
 ['점심값의 총액을 말합니다. is 또는 are를 쓰세요.\nFifteen dollars ___ enough for lunch.','is','15달러라는 총액 하나를 주어로 말하므로 is다.'],
 ['각각의 지폐를 셉니다. is 또는 are를 쓰세요.\nFifteen one-dollar bills ___ in the drawer.','are','중심 명사는 복수 bills다. 총액의 충분함이 아니라 지폐들이 어디 있는지를 말한다.']]);
 extra('none','none은 무조건 단수가 아님','none of 뒤에 불가산명사가 오면 단수로 쓴다. 복수명사일 때는 단수와 복수 용례가 있으며 격식 문체에서는 단수를 선호하는 기준도 있다. 문항의 문맥과 사용역을 확인한다.','무엇이 하나도 없는가',['None of the juice is fresh.','None of the students is here. / None of the students are here.'],[
 ['is 또는 are를 쓰세요.\nNone of the water ___ drinkable.','is','water는 불가산명사이므로 is다.'],
 ['격식 문체와 일상 용례를 모두 포함합니다. is 또는 are 중 가능한 형태 하나를 쓰세요.\nNone of the players ___ ready.',['is','are'],'복수 players를 받는 none of는 단수와 복수로 모두 쓰인다. 이 문제는 사용역을 한쪽으로 한정하지 않았으므로 둘 다 인정한다.']]);
 extra('indefinite','everyone과 어느 한쪽','everyone, someone, nobody 등은 의미상 사람 수와 별개로 문법상 단수다. either/neither of도 격식 문법에서는 단수 일치를 기본으로 연습한다.','여러 사람을 가리켜도 문법상 단수',['Everyone has a seat.','Neither of the answers is correct.'],[
 ['has 또는 have를 쓰세요.\nEveryone in these rooms ___ a badge.','has','주어 everyone은 단수다. rooms는 수식어 안의 복수 명사다.'],
 ['격식 문법 기준으로 is 또는 are를 쓰세요.\nNeither of these routes ___ safe.','is','neither of는 격식 문법의 단수 일치 기준에서 is다. 일상 영어의 복수 용례까지 금지하는 설명은 아니다.'],
 ['격식 문법 기준으로 is 또는 are를 쓰세요.\nEither of the answers ___ acceptable.','is','둘 중 어느 하나라는 either에 맞춰 단수 is를 쓴다. either 자체는 부정어가 아니다.']]);
 extra('rich','사람 집단을 뜻하는 the rich','the rich나 the poor가 각각 부유한 사람들, 가난한 사람들을 뜻하면 복수 동사를 쓴다. the + 형용사라는 모양이 언제나 복수인 것은 아니다.','부유한 사람들 = 복수',['The rich are not a single uniform group.','The poor need access to education.'],[
 ['부유한 사람들을 뜻합니다. is 또는 are를 쓰세요.\nThe rich ___ affected by the new tax.','are','the rich는 이 문장에서 부유한 사람들을 집단적으로 가리키는 복수 표현이다.'],
 ['가난한 사람들을 뜻합니다. need 또는 needs 중 하나를 쓰세요.\nThe poor ___ affordable housing.','need','사람 집단인 the poor는 복수 동사 need와 일치한다.']]);
 extra('both','both가 묶는 자리 확인','both A and B로 두 주어를 연결하면 복수 동사를 쓴다. 하지만 He is both kind and patient처럼 both가 보어를 연결하면 주어 He는 그대로 단수다. both라는 단어만 보고 동사를 바꾸지 않는다.','주어 둘인지 / 보어 둘인지',['Both Mina and Joon are ready.','Mina is both a teacher and a writer.'],[
 ['방문자는 누나와 남동생, 서로 다른 두 명입니다. is 또는 are를 쓰세요.\nBoth my sister and my brother ___ here.','are','both가 서로 다른 두 사람을 주어로 연결하므로 are다.'],
 ['민지는 교사이면서 작가인 한 명입니다. is 또는 are를 쓰세요.\nMinji ___ both a teacher and a writer.','is','주어는 Minji 한 명이다. both는 동사 뒤에서 역할 두 개를 연결하므로 단수 is를 바꾸지 않는다.']]);
 extra('unit','구·절 하나를 주어로','동명사구·to부정사구·that절 하나가 주어로 쓰이면 단수로 취급한다. 행동이 실제로 몇 번인지가 아니라 주어인 구나 절을 하나로 보는 구조다.','하나의 활동·내용',['Reading novels is relaxing.','That he arrived early is surprising.'],[
 ['is 또는 are를 쓰세요.\nLearning new languages ___ rewarding.','is','Learning new languages라는 동명사구 전체가 하나의 주어다. languages에 맞추지 않는다.'],
 ['is 또는 are를 쓰세요.\nThat the students arrived early ___ surprising.','is','that절 전체가 주어다. 절 안의 students는 arrived의 주어이고, 바깥 is는 that절 하나에 맞춘다.']]);
 bank[id('neither')].variants.push(
  {type:'text',question:'격식 문법 기준으로 is 또는 are를 쓰세요.\nEither the receptionist or the managers ___ available.',answers:['are'],explanation:'either는 둘 중 하나라는 선택이다. 동사 가까이의 managers가 복수이므로 are다.'},
  {type:'text',question:'격식 문법 기준으로 is 또는 are를 쓰세요.\nNot only the captain but also the players ___ ready.',answers:['are'],explanation:'주어를 잇는 not only A but also B는 이 예문에서 가까운 players에 맞춰 are를 쓴다. 뜻은 선택이 아니라 A뿐 아니라 B도라는 강조다.'});
 bank['grammar-agreement-each'].variants.push(
  {type:'text',question:'has 또는 have를 쓰세요.\nEvery boy and every girl ___ a seat.',answers:['has'],explanation:'every가 각 단수 명사에 붙어 각각 한 명씩 보므로 단수 has다. 단순한 A and B 주어와 구분한다.'},
  {type:'text',question:'has 또는 have를 쓰세요.\nEach driver and each passenger ___ a ticket.',answers:['has'],explanation:'each가 각 단수 명사에 붙어 하나하나 가리키므로 단수 has다.'});
 bank['grammar-agreement-portion'].variants.push(
  {type:'text',question:'is 또는 are를 쓰세요.\nMost of the furniture ___ old.',answers:['is'],explanation:'무엇의 대부분인지 보면 불가산명사 furniture다. is를 쓴다.'},
  {type:'text',question:'is 또는 are를 쓰세요.\nAll of the chairs ___ broken.',answers:['are'],explanation:'all of 뒤의 대상 chairs가 복수이므로 are다.'});
 // New applications of the agreement document. Append to preserve existing written variants.
 function agreementChoice(key,question,choices,correctIndex,explanation){
  bank[key].variants.push({type:'choice',question,choices,correctIndex,explanation});
 }
 agreementChoice(id('as-well'),
  '격식 문법 기준으로 두 빈칸에 들어갈 말을 순서대로 고르세요.\nThe technicians as well as their supervisor ___ access to the lab.\nThe supervisor, as well as the technicians, ___ access to the lab.',
  ['has / have','have / have','have / has','has / has'],2,
  '첫 문장의 중심 주어는 복수 technicians이므로 have, 둘째는 단수 supervisor이므로 has다. as well as 뒤의 덧붙임을 지우고 남는 주어를 본다. 쉼표가 있거나 없다는 이유로 일치 기준이 바뀌지는 않는다.');
 agreementChoice(id('neither'),
  '격식 문법 기준으로 두 빈칸에 들어갈 말을 순서대로 고르세요.\nNot only the technician but also the assistants ___ ready.\nNeither the assistants nor the technician ___ ready.',
  ['is / are','are / are','is / is','are / is'],3,
  '주어들을 동사 앞에서 잇는 이 두 구문은 동사에 가까운 쪽에 맞춘다. 첫 문장은 assistants가 복수라 are, 둘째는 technician이 단수라 is다. not only는 둘 다 포함하는 강조이고 neither는 둘 다 부정한다. 뜻이 같아서 같은 일치 기준을 쓰는 것은 아니다.');
 agreementChoice(id('knowledge'),
  '다음 문장 중 대괄호 안 동사의 수일치가 틀린 문장을 고르세요.',
  ['The labels on these boxes [are] clear.','The list of required documents [are] on my desk.','The key to the storage rooms [is] missing.','Instructions for the new printer [are] available online.'],1,
  'The list of required documents의 중심 주어는 list 하나이므로 are를 is로 고쳐야 한다. 나머지는 각각 labels → are, key → is, Instructions → are로 맞다. 동사와 가까운 documents·rooms·printer가 아니라 각 문장의 중심 주어를 확인한다.');
 agreementChoice(id('debate-head'),
  '두 빈칸에 들어갈 말을 순서대로 고르세요.\nI know a technician who ___ the servers.\nI know several technicians who ___ the servers.',
  ['maintains / maintain','maintain / maintains','maintains / maintains','maintain / maintain'],0,
  '첫 who는 a technician 한 명을 받아 maintains, 둘째 who는 several technicians 여러 명을 받아 maintain이다. 관계절 안에서 who를 그 앞의 명사로 바꾸면 A technician maintains와 Technicians maintain이 된다. 주절의 I나 목적어 servers에 관계절 동사를 맞추지 않는다.');
 agreementChoice('grammar-agreement-each',
  '격식 문법 기준으로 대괄호 안 동사의 수일치가 틀린 문장을 고르세요.',
  ['The employees each [have] a locker.','Every driver [has] a ticket.','Each of my neighbors [has] a bicycle.','Each of the employees [have] a locker.'],3,
  'Each of the employees에서는 each가 중심이므로 have를 has로 고친다. The employees each에서는 employees가 주어라 have가 맞다. Every driver는 한 명씩 가리키므로 has, Each of my neighbors도 each에 맞춰 has다. each라는 단어가 있는지만 보지 말고 주어 자리를 확인한다.');
 agreementChoice('grammar-agreement-number',
  '두 빈칸에 들어갈 말을 순서대로 고르세요.\nA number of files on this computer ___ damaged.\nThe number of damaged files ___ small.',
  ['is / is','are / is','is / are','are / are'],1,
  'A number of files는 여러 파일을 가리켜 are다. The number of damaged files는 손상된 파일의 수라는 숫자 하나를 가리켜 is다. 첫 문장의 computer나 둘째 문장의 files처럼 뒤에 있는 명사에 끌려가지 않는다.');
 agreementChoice('grammar-agreement-portion',
  '두 빈칸에 들어갈 말을 순서대로 고르세요.\nThirty percent of the equipment ___ new.\nThirty percent of the machines ___ new.',
  ['are / is','are / are','is / is','is / are'],3,
  '첫 문장은 불가산명사 equipment의 일부이므로 is, 둘째는 복수 machines의 일부이므로 are다. 30이라는 숫자나 percent만 보지 않고 무엇의 30%인지를 확인한다.');
 agreementChoice('grammar-agreement-pair',
  '다음 문장 중 대괄호 안 동사의 수일치가 틀린 문장을 고르세요.',
  ['These scissors [is] very sharp.','A pair of trousers [is] on the bed.','Two pairs of gloves [are] in the drawer.','Those trousers [are] clean.'],0,
  'scissors는 복수형으로 취급하므로 is를 are로 고친다. 가위가 실제로 한 개여도 scissors 자체에는 복수 동사를 쓴다. 나머지는 단수 pair → is, 복수 pairs → are, 복수형 trousers → are로 맞다.');
 agreementChoice('grammar-agreement-identity',
  '첫 문장에는 누나 수진과 남동생 도현, 서로 다른 두 명이 방문했습니다.\nMy sister and brother ___ here.\n둘째 문장의 방문자는 준호 한 명이며, 준호가 내 친구이면서 동료입니다.\nMy friend and colleague ___ here.\n두 빈칸에 들어갈 말을 순서대로 고르세요.',
  ['is / are','is / is','are / is','are / are'],2,
  '첫 문장은 서로 다른 두 사람이라 are, 둘째는 한 사람의 두 역할이라 is다. 두 문장 모두 my를 한 번만 썼지만 정답이 다르다. 소유격의 개수만으로 인원수를 정하지 말고, 제시된 문맥에서 한 명인지 두 명인지 확인한다.');
 agreementChoice('grammar-agreement-together',
  '격식 문법 기준으로 두 빈칸에 들어갈 말을 순서대로 고르세요.\nThe engineers, including their manager, ___ here.\nThe manager, together with the engineers, ___ here.',
  ['are / is','is / are','are / are','is / is'],0,
  '첫 문장은 engineers가 복수라 are, 둘째는 manager가 단수라 is다. including과 together with로 덧붙인 부분은 중심 주어를 바꾸지 않는다. 두 문장을 각각 The engineers are here와 The manager is here로 줄여 본다.');
 agreementChoice('grammar-agreement-existential',
  '격식 문법 기준으로 두 빈칸에 들어갈 말을 순서대로 고르세요.\nNear the door ___ two empty boxes.\nThere ___ a spare key in this drawer.',
  ['is / are','are / are','are / is','is / is'],2,
  '첫 문장은 장소 표현을 앞으로 보낸 도치다. 뒤의 two empty boxes가 주어이므로 are다. 둘째 there 구문에서는 뒤의 a spare key가 단수라 is다. door나 drawer는 장소를 설명하는 말이며 일치 기준이 아니다.');
 agreementChoice('grammar-agreement-collective',
  '영국식 용례도 포함하며 집단을 하나로 보는지 구성원 각각으로 보는지 문맥을 한정하지 않습니다. 두 빈칸에 가능한 형태를 빠짐없이 제시한 보기를 고르세요.\nThe committee ___ ready.\nThe members of the committee ___ ready.',
  ['is만 / are','is 또는 are / are','are만 / is','is 또는 are / is'],1,
  '첫 committee는 집합명사라 집단 하나를 뜻하는 is와 구성원들을 떠올리는 영국식 are 용례가 모두 있다. 둘째는 중심 주어 members가 분명한 복수라 are다. committee가 들어 있다는 이유만으로 두 문장에 같은 기준을 적용하지 않는다.');
 agreementChoice('grammar-agreement-noun-form',
  'police는 경찰관들을, physics는 학문 이름을 뜻합니다. 대괄호 안 동사의 수일치가 틀린 문장을 고르세요.',
  ['The news [is] surprising.','The police [are] investigating the case.','Information about these courses [is] available online.','Physics [are] my favorite subject.'],3,
  '학문 이름 Physics는 단수로 취급하므로 are를 is로 고친다. news도 단수라 is, 경찰관들을 뜻하는 police는 복수라 are다. Information은 불가산명사라 is이며 courses의 복수형에 맞추지 않는다.');
 agreementChoice('grammar-agreement-one',
  '일반적인 격식 문법 기준으로 대괄호 안 동사의 수일치가 틀린 문장을 고르세요.',
  ['One of the train doors [is] open.','Several passengers [have] complained.','More than one passenger [have] complained.','The doors of the train [are] open.'],2,
  'more than one + 단수명사 passenger는 보통 단수 동사를 쓰므로 have를 has로 고친다. 의미가 두 명 이상이어도 이 구문의 기본 일치는 단수다. 나머지는 one → is, Several passengers → have, doors → are로 맞다.');
 agreementChoice('grammar-agreement-amount',
  '첫 문장은 작업에 필요한 시간의 총량, 둘째는 시계 두 개의 위치를 말합니다. 두 빈칸에 들어갈 말을 순서대로 고르세요.\nTwo hours ___ enough to finish this task.\nTwo clocks ___ hanging on the wall.',
  ['is / are','are / is','is / is','are / are'],0,
  '첫 문장은 두 시간이라는 총량 하나가 충분한지를 말하므로 is다. 둘째는 실제 물건인 시계 두 개를 복수 명사 clocks로 세므로 are다. 숫자 two가 있다는 사실만으로 두 동사를 모두 복수로 정하지 않는다.');
 agreementChoice('grammar-agreement-none',
  '격식 문체와 일상 용례를 모두 포함합니다. 두 빈칸에 가능한 형태를 빠짐없이 제시한 보기를 고르세요.\nNone of the furniture ___ damaged.\nNone of the chairs ___ damaged.',
  ['is / is만','are / are만','are / is 또는 are','is / is 또는 are'],3,
  'furniture는 불가산명사라 첫 빈칸에는 is를 쓴다. 복수 chairs를 받는 none of에는 is와 are 용례가 모두 있다. 둘째 문장의 문체를 한쪽으로 제한하지 않았으므로 어느 하나만 가능하다고 말한 보기는 맞지 않는다.');
 agreementChoice('grammar-agreement-indefinite',
  '두 빈칸에 들어갈 말을 순서대로 고르세요.\nNobody in these buildings ___ access to the roof.\nSeveral of the residents ___ bicycles.',
  ['have / has','has / have','has / has','have / have'],1,
  'nobody는 문법상 단수라 has다. buildings는 주어를 수식하는 전치사구 안의 명사다. 둘째는 여러 주민을 가리키는 several of the residents이므로 have다. 실제 사람이 여러 명 관련돼 있다는 뜻과 문법상 주어의 수를 구별한다.');
 agreementChoice('grammar-agreement-rich',
  'the rich는 부유한 사람들, the poor는 가난한 사람들을 가리킵니다. 두 빈칸에 들어갈 말을 순서대로 고르세요.\nThe rich ___ not immune to illness.\nThe poor ___ not a uniform group.',
  ['is / are','are / is','are / are','is / is'],2,
  '두 주어 모두 사람들을 집단적으로 가리키므로 are / are다. 둘째 문장의 a uniform group은 주어가 아니라 보어다. 동사를 뒤의 단수형 group에 맞추지 않는다.');
 agreementChoice('grammar-agreement-both',
  '미나는 과학자이면서 소설가인 한 명이며, 편집자는 미나와 다른 사람입니다. 두 빈칸에 들어갈 말을 순서대로 고르세요.\nMina ___ both a scientist and a novelist.\nBoth Mina and her editor ___ here.',
  ['are / is','is / are','is / is','are / are'],1,
  '첫 문장은 주어 Mina가 한 명이라 is다. both는 동사 뒤에서 두 역할을 연결한다. 둘째는 both가 Mina와 her editor라는 두 주어를 연결하므로 are다. both라는 단어가 보이면 먼저 무엇을 연결하는지 본다.');
 agreementChoice('grammar-agreement-unit',
  '두 빈칸에 들어갈 말을 순서대로 고르세요.\nThat the prices have risen ___ clear.\nTo repair these machines ___ time.',
  ['is / takes','are / take','is / take','are / takes'],0,
  '첫 문장의 주어는 That the prices have risen이라는 절 전체라 is다. 절 안의 prices는 have risen의 주어일 뿐, 바깥 빈칸의 일치 기준이 아니다. 둘째는 To repair these machines라는 to부정사구 하나가 주어라 단수 takes를 쓴다. 목적어 machines에 맞춰 take로 바꾸지 않는다.');
 // PART 01 문장의 구조·동사 유형(001~030) 정리를 적용한 자체 제작 문항.
 // 원서의 예문은 쓰지 않고, 같은 규칙을 다른 어휘·상황의 새 문장으로 다시 만들었다.
 // 객관식은 9급 어법 문항과 같은 형식이다. 네 문장 중 어법상 옳지 않은 하나가 정답이고,
 // 나머지 세 문장은 같은 정리의 다른 규칙을 지킨 옳은 문장이라 오답을 읽어도 배우는 것이 있다.
 // 문제집 Day 1 — PART 01 문장의 구조·동사 유형. 60문제(4지선다 40 · 직접 쓰기 20)이고 한 줄이 곧 문제 하나다.
 // 문장은 검토를 마친 원고(day1-60.json)를 한 글자도 바꾸지 않고 옮겼다. lesson은 해설 화면에 함께 나오는 규칙 정리이며,
 // 이전 Day 1 규칙 카드 12개의 정리 문장을 그대로 쓴다. point는 그 문제가 훈련하는 문법 포인트이고, 같은 point의 문제는
 // review-policy.js에서 한 개념으로 묶여 하나를 틀리면 나머지가 형제 간격 뒤에 이어서 나온다.
 const DAY1_LESSONS={
  "preposition":{"title":"전치사를 넣을 자리와 넣지 않을 자리","rule":"introduce·explain·suggest·announce는 전달하는 내용을 목적어로 두고 듣는 사람은 to로 연결한다. 사람을 먼저 쓰는 4형식으로는 쓰지 않는다. 반대로 approach·discuss·enter·marry·reach·resemble·answer는 목적어를 바로 받는 타동사라 전치사를 넣지 않는다. wait처럼 목적어를 바로 받지 못하는 동사에는 for가 반드시 필요하다.","hook":"한국어 “~에게·~에”를 전치사로 그대로 옮기지 않기","examples":["The guide explained the rules to the visitors.","The reporter approached the mayor after the vote.","We are waiting for the results."]},
  "question-form":{"title":"간접의문문과 부가의문문","rule":"의문사절이 다른 동사의 목적어로 들어가면 의문사 + 주어 + 동사라는 평서문 어순이 되고, 의문문의 도치를 쓰지 않는다. 부가의문문은 주절의 주어와 동사에 맞춘다. 뒤에 딸린 that절의 주어와 동사에 맞추지 않는다.","hook":"안에 든 절은 평서문 어순 / 꼬리표는 주절 기준","examples":["I do not know when the office opens.","She thinks that he is honest, doesn’t she?"]},
  "linking":{"title":"2형식 동사 뒤의 보어","rule":"taste·smell·sound·look·feel처럼 감각을 나타내는 동사는 주어의 상태를 설명하므로 보어에 부사가 아니라 형용사를 쓴다. remain·stay처럼 상태가 이어짐을 말하는 동사도 보어를 두며, 주어가 동작을 받은 상태라면 과거분사를 보어로 쓴다.","hook":"주어를 설명하는 자리 → 형용사·과거분사","examples":["This soup tastes salty.","Please remain seated until the bus stops."]},
  "lookalike":{"title":"형태가 겹쳐서 헷갈리는 동사","rule":"lie(눕다·놓여 있다)는 lie-lay-lain으로 목적어가 없고, lay(놓다)는 lay-laid-laid로 목적어가 있다. lie의 과거형이 lay라서 두 동사가 겹쳐 보인다. find(찾다)는 find-found-found, found(설립하다)는 found-founded-founded다. 철자가 같아 보이는 지점에서 뜻과 목적어 유무를 확인한다.","hook":"lie의 과거가 lay / found는 서로 다른 두 동사","examples":["Infants lie face down when they sleep.","She laid the documents on the desk.","They founded the company in 1998."]},
  "no-passive":{"title":"수동태를 쓰지 않는 자리","rule":"rise(오르다)는 목적어가 없는 자동사라 수동태로 쓰지 않는다. 값을 올리는 타동사는 raise다. sell·read·wash처럼 일부 동사는 능동형 그대로 “잘 팔린다·잘 읽힌다”라는 수동의 뜻을 나타내며, 이때도 수동태로 바꾸지 않는다.","hook":"자동사 rise / 능동형으로 수동 뜻인 sell","examples":["Rents have risen sharply this year.","The landlord raised the rent again.","Her first novel sold surprisingly well."]},
  "gerund-only":{"title":"동명사만 목적어로 쓰는 동사","rule":"resist·admit·avoid·deny·mind·postpone·enjoy·finish는 목적어로 동명사를 쓰고 to부정사를 쓰지 않는다. 목적어가 동작을 받는 뜻이면 being + 과거분사 형태의 동명사가 된다.","hook":"이 동사들 뒤에는 -ing","examples":["He avoided answering the question.","They postponed announcing the result."]},
  "object-voice":{"title":"목적어가 동작을 받을 때의 보어","rule":"목적어가 동작을 직접 하면 목적격보어에 현재분사나 원형을 쓰고, 목적어가 동작을 받으면 과거분사를 쓴다. 형태는 앞의 동사가 정한다. see·hear·listen to 같은 지각동사와 keep·have는 과거분사를 바로 쓰고, let·make 같은 사역동사는 원형 자리에 be + 과거분사를 넣으며, want·expect는 to be + 과거분사를 쓴다.","hook":"목적어가 하는가 받는가 → 형태는 앞 동사가 결정","examples":["I saw the gate locked from the inside.","Keep me informed about the schedule.","Do not let the paint be exposed to sunlight.","I want this form to be signed today."]},
  "object-form":{"title":"동사가 정해 주는 목적어 뒤 형태","rule":"encourage·allow·advise·cause·force·persuade는 목적어 뒤에 to부정사를 쓴다. make·let·have는 원형부정사를 쓴다. keep·prevent·stop·discourage는 A from -ing로 “A가 ~하지 못하게 하다”를 나타낸다. 뜻이 비슷해도 동사마다 뒤에 오는 형태가 정해져 있다.","hook":"뜻이 아니라 동사별로 고정된 형태","examples":["The city encouraged residents to recycle.","The noise made everyone leave early.","The strike kept us from reaching the airport."]},
  "prep-pair":{"title":"A of B와 A as B 짝","rule":"accuse A of B는 “A를 B의 이유로 고발·비난하다”이며 of 뒤에는 명사나 -ing가 온다. think of A as B·regard A as B·refer to A as B는 “A를 B로 여기다·부르다”로 as가 짝이다. 동사마다 붙는 전치사가 정해져 있으므로 뜻이 비슷하다고 바꿔 쓰지 않는다.","hook":"이유는 of / 자격·명칭은 as","examples":["They accused the clerk of leaking the file.","Many people think of him as a pioneer."]},
  "infinitive-gerund":{"title":"to부정사와 동명사의 뜻 차이","rule":"forget·remember·regret·stop은 뒤에 오는 형태에 따라 뜻이 달라진다. to부정사는 앞으로 할 일이나 지금 하려는 목적을 가리키고, 동명사는 이미 한 일을 가리킨다. stop -ing는 하던 일을 그만두는 것이고, stop to do는 무엇을 하려고 잠시 멈추는 것이다.","hook":"to는 앞으로 할 일 / -ing는 이미 한 일","examples":["Do not forget to lock the door.","I regret telling her the truth.","He stopped to answer the phone."]},
  "finite":{"title":"명사의 전치사와 문장의 본동사","rule":"명사 demand는 무엇에 대한 수요인지를 for로 연결한다. 또 문장에는 반드시 본동사가 있어야 하므로, 주어부가 길어도 being·having 같은 분사가 서술어를 대신할 수 없다.","hook":"demand for ~ / 서술어는 분사가 아니라 정동사","examples":["The demand for electric cars is rising.","The reason for the delay was a broken signal box."]},
  "it-takes":{"title":"It takes 시간 to do","rule":"It takes + (사람) + 시간 + to부정사로 “~하는 데 시간이 걸린다”를 나타낸다. It은 가주어이고 실제 내용은 to부정사가 맡는다. 시간을 주어로 올려 수동태로 바꾸거나, to부정사 대신 for -ing를 쓰지 않는다.","hook":"가주어 It + take + 시간 + to do","examples":["It takes about ten minutes to walk there.","It took her three years to finish the thesis."]}
 };
 const DAY1=[
  {"n":1,"point":"4형식 불가(introduce/explain/suggest/announce + to)","lesson":"preposition","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["The host introduced the guest speaker to the audience.","The pharmacist explained me how to take the new tablets.","We reached the harbor just as the morning fog began to lift.","The passengers were waiting for the shuttle in the pouring rain."],"correctIndex":1,"explanation":"정답 근거: explain은 설명하는 내용을 목적어로 두고, 듣는 사람은 to로 연결한다. 사람을 바로 목적어로 쓰는 4형식(explain me ~)은 쓰지 않으므로 explained to me how to take the new tablets로 고친다.\n\n보기 비교: ① introduce A to B로 소개할 사람을 목적어, 듣는 사람을 to로 연결해 옳다. ③ reach는 전치사 없이 목적어를 받는 타동사라 reached the harbor가 옳다. ④ wait는 목적어를 바로 받지 못하므로 waiting for the shuttle이 옳다.\n\n기억 연결: explain · introduce · suggest · announce → “~에게”는 늘 to + 사람. explain me(X) / explain to me(O)."},
  {"n":2,"point":"4형식 불가(introduce/explain/suggest/announce + to)","lesson":"preposition","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["The chairman announced the staff the merger on Monday.","She suggested me a quicker route to the train station.","Let me introduce you my cousin who lives in Toronto.","The clerk explained the refund policy to the customer."],"correctIndex":3,"explanation":"정답 근거: explain은 설명하는 내용(the refund policy)을 목적어로 두고 듣는 사람(the customer)을 to로 연결했으므로 옳다.\n\n보기 비교: ① announce도 4형식을 쓰지 않으므로 announced the merger to the staff로 고친다. ② suggest도 suggested a quicker route to me로 고친다. ③ introduce도 사람을 먼저 쓰지 않으므로 introduce my cousin ... to you로 고친다.\n\n기억 연결: announce · suggest · introduce · explain → 내용이 먼저, 사람은 뒤에 to로. “give처럼 사람을 앞에 두는” 동사가 아니다."},
  {"n":3,"point":"타동사에 전치사 금지","lesson":"preposition","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["A stranger approached to our table and asked for directions.","The committee will discuss the proposed budget cuts next Tuesday.","My younger daughter resembles her grandmother more every year.","Nobody answered the phone at the front desk last night."],"correctIndex":0,"explanation":"정답 근거: approach는 목적어를 바로 받는 타동사다. 한국어 “테이블로 다가왔다”에 끌려 to를 넣으면 틀리므로 approached our table로 고친다.\n\n보기 비교: ② discuss도 전치사 없이 목적어(the budget cuts)를 받아 옳다. ③ resemble도 resembles her grandmother로 옳다. ④ answer도 answered the phone으로 옳다.\n\n기억 연결: approach → 바로 목적어. approach to(X). 같은 무리: discuss · enter · marry · reach · resemble · answer."},
  {"n":4,"point":"타동사에 전치사 금지","lesson":"preposition","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["Two security guards entered the empty lobby at midnight.","The panel discussed the new safety standards for an hour.","The hikers finally reached at the mountain cabin after sunset.","The famous actress married a young pilot she had met in Lisbon."],"correctIndex":2,"explanation":"정답 근거: reach는 도착 지점을 바로 목적어로 받는 타동사다. arrive at과 섞어 at을 넣으면 틀리므로 reached the mountain cabin으로 고친다.\n\n보기 비교: ① enter는 entered the lobby처럼 전치사 없이 옳다. ② discuss도 discussed the standards로 옳다. ④ marry도 married a pilot으로 옳다.\n\n기억 연결: reach → 바로 목적어(reach the cabin). 전치사가 필요한 것은 arrive at · get to 쪽이다."},
  {"n":5,"point":"타동사에 전치사 금지","lesson":"preposition","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["The small plane approached the runway through heavy rain.","The lawyers discussed the terms of the contract in private.","It takes about ten minutes to reach the station on foot.","My uncle married with a nurse from the local hospital."],"correctIndex":3,"explanation":"정답 근거: marry는 결혼 상대를 바로 목적어로 받는 타동사라 with를 넣지 않는다. married a nurse로 고친다.\n\n보기 비교: ① approach는 approached the runway로 옳다. ② discuss도 discussed the terms로 옳다. ③ It takes + 시간 + to부정사 구조이고, reach도 the station을 바로 목적어로 받아 옳다.\n\n기억 연결: marry → 바로 목적어(marry a nurse). 상태를 말할 때만 be married to. marry with(X)."},
  {"n":6,"point":"타동사에 전치사 금지","lesson":"preposition","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["The twins resemble with each other in their voices.","We discussed about the new work schedule over lunch.","The office answered every complaint within a week.","The young deer approached to the fence very slowly."],"correctIndex":2,"explanation":"정답 근거: answer는 목적어를 바로 받는 타동사이므로 answered every complaint가 옳다.\n\n보기 비교: ① resemble은 전치사 없이 resemble each other로 고친다. ② discuss도 discussed the new work schedule로 고친다(about 삭제). ④ approach도 approached the fence로 고친다.\n\n기억 연결: resemble · discuss · approach · answer → “~와 · ~에 대해 · ~에게”라는 한국어에 속지 말고 전치사 없이."},
  {"n":7,"point":"부가의문문(주절 기준)","lesson":"question-form","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["You think the museum opens at nine, don’t you?","The guests have already left the hotel, haven’t they?","She believes that the plan will work, won’t it?","Your brother seldom calls home these days, does he?"],"correctIndex":2,"explanation":"정답 근거: 부가의문문은 주절 She believes에 맞춘다. 일반동사 현재 3인칭 단수 긍정이므로 doesn’t she로 고친다. that절의 the plan will work에 맞춘 won’t it은 틀리다.\n\n보기 비교: ① 주절 You think에 맞춘 don’t you라 옳다. ② 현재완료 긍정이라 haven’t they가 옳다. ④ seldom이 이미 부정의 뜻이라 긍정형 does he가 옳다.\n\n기억 연결: believe · think · say + that절 → 꼬리는 앞의 주어(She believes → doesn’t she)에 붙인다."},
  {"n":8,"point":"remain + p.p.","lesson":"linking","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["Please remain seating until the pilot turns off the sign.","The museum remained closed for repairs during the whole winter.","The fresh coffee smells wonderful this morning.","The unopened letter lay on his desk for a week."],"correctIndex":0,"explanation":"정답 근거: 승객은 좌석에 앉혀진 상태로 있어야 하므로 remain 뒤에 과거분사 seated를 쓴다. remain seating으로는 쓰지 않으므로 remain seated로 고친다.\n\n보기 비교: ② 박물관이 닫힌 상태로 있었으므로 remained closed가 옳다. ③ smell 뒤에 형용사 wonderful을 쓴 2형식이라 옳다. ④ lay는 자동사 lie(놓여 있다)의 과거형이라 옳다.\n\n기억 연결: remain · stay + 상태 → seated · closed처럼 과거분사. “자리에 앉아 계세요” = remain seated."},
  {"n":9,"point":"lie/lay","lesson":"lookalike","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["She laid a clean towel over the chair to dry.","The workers have lain new tiles in the bathroom.","These documents have lain in the safe since 1990.","The hens laid fewer eggs during the cold spell."],"correctIndex":1,"explanation":"정답 근거: new tiles라는 목적어가 있으므로 “놓다·깔다”인 타동사 lay를 써야 하고, 그 과거분사는 laid다. have laid new tiles로 고친다. lain은 목적어가 없는 자동사 lie의 과거분사다.\n\n보기 비교: ① a clean towel이라는 목적어가 있어 laid가 옳다. ③ 서류가 스스로 놓여 있는 것이라 자동사 lie의 과거분사 lain이 옳다. ④ lay eggs(알을 낳다)의 과거형 laid라 옳다.\n\n기억 연결: lay-laid-laid(목적어 O) / lie-lay-lain(목적어 X). 목적어가 보이면 laid."},
  {"n":10,"point":"lie/lay","lesson":"lookalike","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["The old dog lay in the shade all afternoon.","He lay the heavy box down on the kitchen floor.","Your phone has laid on the counter since breakfast.","I usually lay on the sofa after a long night shift."],"correctIndex":0,"explanation":"정답 근거: 눕는 동작에는 목적어가 없으므로 자동사 lie를 쓰고, 과거 이야기라 과거형 lay가 옳다.\n\n보기 비교: ② the heavy box라는 목적어가 있으므로 타동사 lay의 과거형 laid로 고친다. ③ 전화기가 스스로 놓여 있는 것이라 has lain으로 고친다. ④ 습관적으로 눕는 것이므로 자동사 lie의 현재형 lie로 고친다.\n\n기억 연결: lie(눕다) → lay(과거) → lain / lay(놓다) → laid → laid. “과거 lay”와 “현재 lay”를 목적어로 구별."},
  {"n":11,"point":"found/find","lesson":"lookalike","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["Her grandmother founded a small bakery in 1952.","Rescuers found the missing hiker near a frozen stream.","The two brothers founded the lost key under the rug.","The river rose quickly after three days of heavy rain."],"correctIndex":2,"explanation":"정답 근거: 잃어버린 열쇠는 “설립하는” 대상이 아니라 “찾는” 대상이므로 find의 과거형 found를 써서 found the lost key로 고친다.\n\n보기 비교: ① 빵집을 세웠다는 뜻이라 found(설립하다)의 과거형 founded가 옳다. ② 등산객을 찾았다는 뜻이라 find의 과거형 found가 옳다. ④ rise(오르다)의 과거형 rose라 옳다.\n\n기억 연결: find-found-found(찾다) / found-founded-founded(설립하다). 회사 · 학교 · 가게면 founded, 물건 · 사람이면 found."},
  {"n":12,"point":"능동형 수동 의미(sell/read/wash)","lesson":"no-passive","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["The new phone model sells well among teenagers.","The price of eggs has been risen again this month.","She laid down on the bed as soon as she got home.","They introduced us their new business partner."],"correctIndex":0,"explanation":"정답 근거: sell은 주어가 상품일 때 능동형 그대로 “잘 팔린다”라는 뜻을 나타내므로 sells well이 옳다.\n\n보기 비교: ② rise는 자동사라 수동태가 없으므로 has risen으로 고친다. ③ 목적어 없이 눕는 것이므로 lay down(lie의 과거)으로 고친다. ④ introduce는 4형식을 쓰지 않으므로 introduced their new business partner to us로 고친다.\n\n기억 연결: sell · read · wash + well/easily → 능동형으로 “잘 팔린다 · 잘 읽힌다 · 잘 빨린다”."},
  {"n":13,"point":"능동형 수동 의미(sell/read/wash)","lesson":"no-passive","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["The tenants resisted to leave their old apartments.","This cotton shirt washes well even in cold water.","The heavy fog caused the ferry leave two hours late.","The rain prevented us to finish the soccer game."],"correctIndex":1,"explanation":"정답 근거: wash는 주어가 옷감일 때 능동형 그대로 “세탁이 잘된다”라는 뜻을 나타내므로 washes well이 옳다.\n\n보기 비교: ① resist는 동명사를 목적어로 쓰므로 resisted leaving으로 고친다. ③ cause는 목적어 뒤에 to부정사를 쓰므로 caused the ferry to leave로 고친다. ④ prevent는 A from -ing이므로 prevented us from finishing으로 고친다.\n\n기억 연결: wash · sell · read → 사물 주어 + 능동형 + well = 수동의 뜻. 굳이 is washed로 바꾸지 않는다."},
  {"n":14,"point":"rise/raise(수동 불가)","lesson":"no-passive","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["The landlord raised the rent by five percent.","Sea levels have risen steadily over the past century.","Several parents raised concerns about the lunch menu.","Bus fares were risen twice during the last year."],"correctIndex":3,"explanation":"정답 근거: rise는 목적어가 없는 자동사라 수동태가 없다. 요금이 올랐다면 rose, 누군가 올렸다는 뜻이라면 타동사 raise를 써서 were raised로 고친다.\n\n보기 비교: ① the rent라는 목적어가 있어 타동사 raised가 옳다. ② 해수면이 스스로 오른 것이라 자동사 rise의 현재완료 have risen이 옳다. ③ concerns를 목적어로 받는 타동사 raised(제기하다)라 옳다.\n\n기억 연결: rise-rose-risen(자동사, be risen 불가) / raise-raised-raised(타동사, be raised 가능)."},
  {"n":15,"point":"간접의문문 어순","lesson":"question-form","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["Can you tell me where the nearest pharmacy is?","Nobody knows who will replace the head coach.","I have no idea why is the printer jammed again.","We asked the guide how long the tour would last."],"correctIndex":2,"explanation":"정답 근거: why절이 idea 뒤에 들어간 간접의문문이므로 의문사 + 주어 + 동사 어순을 써서 why the printer is jammed again으로 고친다.\n\n보기 비교: ① where the nearest pharmacy is로 평서문 어순이라 옳다. ② who가 절의 주어라 who will replace가 그대로 옳다. ④ how long the tour would last로 평서문 어순이라 옳다.\n\n기억 연결: know · wonder · tell me · have no idea + 의문사 → 그 뒤는 “주어 + 동사”. why is it(X) → why it is(O)."},
  {"n":16,"point":"resist/admit/avoid/deny/mind/postpone + -ing","lesson":"gerund-only","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["We postponed to paint the fence until the weather cleared.","The minister denied receiving any money from the building firm.","I don’t mind waiting outside while you finish your call.","The boy finally admitted breaking the neighbor’s window."],"correctIndex":0,"explanation":"정답 근거: postpone은 동명사만 목적어로 쓰므로 postponed painting the fence로 고친다.\n\n보기 비교: ② deny는 동명사를 목적어로 쓰므로 denied receiving이 옳다. ③ mind도 동명사를 쓰므로 mind waiting이 옳다. ④ admit도 동명사를 쓰므로 admitted breaking이 옳다.\n\n기억 연결: postpone · deny · mind · admit · avoid · resist → 뒤는 -ing. “미루다”도 to가 아니라 -ing."},
  {"n":17,"point":"resist/admit/avoid/deny/mind/postpone + -ing","lesson":"gerund-only","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["She could not resist tasting the cake before dinner.","The mayor postponed signing the new budget plan.","The singer denied having canceled the concert.","He avoided to make eye contact with the interviewer."],"correctIndex":3,"explanation":"정답 근거: avoid는 동명사만 목적어로 쓰므로 avoided making eye contact로 고친다.\n\n보기 비교: ① resist는 동명사를 쓰므로 resist tasting이 옳다. ② postpone도 postponed signing으로 옳다. ③ deny 뒤에 완료 동명사 having canceled를 써서 이전의 일을 부인한 것이라 옳다.\n\n기억 연결: avoid → -ing(avoid making). resist · postpone · deny도 같은 무리."},
  {"n":18,"point":"resist/admit/avoid/deny/mind/postpone + -ing","lesson":"gerund-only","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["The suspect admitted to steal the famous painting.","The prisoner resisted being moved to another cell.","Would you mind to hold the door open for me?","The company postponed to launch the app until May."],"correctIndex":1,"explanation":"정답 근거: resist는 동명사를 목적어로 쓰고, 죄수가 옮겨지는 쪽이므로 수동 동명사 being moved가 옳다.\n\n보기 비교: ① admit은 admitted stealing 또는 admitted to stealing으로 고친다(이때 to는 전치사). ③ mind는 mind holding으로 고친다. ④ postpone은 postponed launching으로 고친다.\n\n기억 연결: resist · admit · mind · postpone → -ing. 당하는 쪽이면 being + p.p.(resisted being moved)."},
  {"n":19,"point":"지각동사/keep/have + p.p.","lesson":"object-voice","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["I heard the church bells ringing in the distance.","She had her hair cut short before the wedding.","Please keep the windows closed during the storm.","We watched the old bridge demolishing by a crane."],"correctIndex":3,"explanation":"정답 근거: 다리는 크레인에 의해 철거되는 대상이므로 지각동사 watch + 목적어 + 과거분사를 써서 watched the old bridge demolished by a crane으로 고친다.\n\n보기 비교: ① 종이 스스로 울리므로 현재분사 ringing이 옳다. ② 머리카락은 잘리는 대상이라 have + O + p.p.(cut)가 옳다. ③ 창문은 닫히는 대상이라 keep + O + p.p.(closed)가 옳다.\n\n기억 연결: watch · hear · see · keep · have + O → O가 “당하면” p.p., “하면” -ing. by가 보이면 p.p."},
  {"n":20,"point":"지각동사/keep/have + p.p.","lesson":"object-voice","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["I saw the thief arresting by two police officers.","He kept the engine run while we loaded the van.","We heard the announcement made over the speakers.","She had her car repair at the garage down the street."],"correctIndex":2,"explanation":"정답 근거: 안내 방송은 “나오게 되는” 대상이므로 지각동사 hear + 목적어 + 과거분사 made가 옳다.\n\n보기 비교: ① 도둑은 체포되는 대상이므로 saw the thief arrested로 고친다. ② 엔진이 계속 돌아가는 것이므로 kept the engine running으로 고친다. ④ 차는 수리되는 대상이므로 had her car repaired로 고친다.\n\n기억 연결: see · hear · keep · have + O + (당하면 p.p. / 하면 -ing). 원형(run · repair)은 이 자리에 오지 않는다."},
  {"n":21,"point":"let + O + be p.p.","lesson":"object-voice","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["Don’t let the children be left alone near the pool.","The storm forced the school to close for two days.","The owner let the old wall paint by local volunteers.","The coach let the injured player rest on the bench for a while."],"correctIndex":2,"explanation":"정답 근거: 벽은 칠해지는 대상이다. let 뒤에는 원형이 오므로 원형 자리에 be + p.p.를 넣어 let the old wall be painted by local volunteers로 고친다.\n\n보기 비교: ① 아이들이 남겨지는 대상이라 let + O + be left가 옳다. ② force는 목적어 뒤에 to부정사를 쓰므로 forced the school to close가 옳다. ④ 선수가 스스로 쉬는 것이라 let + O + 원형 rest가 옳다.\n\n기억 연결: let + O + 원형 / O가 당하면 let + O + be p.p. (let it be painted)."},
  {"n":22,"point":"want/expect + O + to be p.p.","lesson":"object-voice","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["The client wants the logo design be changed again.","The manager expects the report to be finished by noon.","I want these boxes to be moved before the painters arrive.","We expect the new bridge to open to traffic next spring."],"correctIndex":0,"explanation":"정답 근거: want는 목적어 뒤에 to부정사를 쓰고, 로고 디자인은 바뀌는 대상이므로 to be + p.p.가 필요하다. wants the logo design to be changed로 고친다.\n\n보기 비교: ② expect + O + to be finished라 옳다. ③ want + O + to be moved라 옳다. ④ 다리가 스스로 개통하는 것이므로 능동 to부정사 to open이 옳다.\n\n기억 연결: want · expect + O + to. O가 당하면 to be p.p. — let과 달리 to를 빼지 않는다."},
  {"n":23,"point":"encourage/allow/advise/cause/force/persuade + O + to","lesson":"object-form","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["My doctor advised me to cut down on salty food.","Her parents persuaded her to apply for the scholarship.","The strike caused many morning flights to be canceled.","The zoo does not allow visitors feed the animals."],"correctIndex":3,"explanation":"정답 근거: allow는 목적어 뒤에 to부정사를 쓰므로 allow visitors to feed the animals로 고친다.\n\n보기 비교: ① advise + O + to cut이라 옳다. ② persuade + O + to apply라 옳다. ③ cause + O + to be canceled로, 항공편이 취소되는 대상이라 수동 to부정사가 옳다.\n\n기억 연결: allow · advise · persuade · cause · encourage · force + O + to. 사역동사처럼 원형을 쓰지 않는다."},
  {"n":24,"point":"encourage/allow/advise/cause/force/persuade + O + to","lesson":"object-form","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["The teacher encouraged the shy students speak up in class.","The flood forced hundreds of families to leave their homes.","My coach advised me not to skip the warm-up exercises.","The noise stopped me from concentrating on my book."],"correctIndex":0,"explanation":"정답 근거: encourage는 목적어 뒤에 to부정사를 쓰므로 encouraged the shy students to speak up으로 고친다.\n\n보기 비교: ② force + O + to leave라 옳다. ③ advise + O + not to skip으로, 부정어 not은 to 앞에 둔다. ④ stop A from -ing라 옳다.\n\n기억 연결: encourage → O + to do. “격려해서 하게 하다”라도 make처럼 원형을 쓰지 않는다."},
  {"n":25,"point":"encourage/allow/advise/cause/force/persuade + O + to","lesson":"object-form","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["The guard forced the drivers stop at the gate.","Mom will not allow us stay up past midnight.","The heavy traffic caused us to miss the first act.","The salesman persuaded my father buying a new car."],"correctIndex":2,"explanation":"정답 근거: cause는 목적어 뒤에 to부정사를 쓰므로 caused us to miss가 옳다.\n\n보기 비교: ① force는 forced the drivers to stop으로 고친다. ② allow는 allow us to stay up으로 고친다. ④ persuade는 persuaded my father to buy로 고친다.\n\n기억 연결: cause · force · allow · persuade → O + to do. 원형(stop)도 -ing(buying)도 아니다."},
  {"n":26,"point":"make/let/have + 원형","lesson":"object-form","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["The sad ending made the whole audience cry.","The officer had the driver to show his license.","Please let me know when the parcel arrives.","The bright sunlight kept us from seeing the screen."],"correctIndex":1,"explanation":"정답 근거: 사역동사 have는 목적어가 직접 하는 동작을 원형부정사로 쓴다. had the driver show his license로 고친다.\n\n보기 비교: ① make + O + 원형 cry라 옳다. ③ let + O + 원형 know라 옳다. ④ keep A from -ing라 옳다.\n\n기억 연결: make · let · have + O + 원형. have the driver show(O) / to show(X)."},
  {"n":27,"point":"make/let/have + 원형","lesson":"object-form","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["Her silly jokes always make me to laugh.","Let the kids to choose their own snacks.","The coach made us running around the field.","I had the plumber fix the leaking pipe."],"correctIndex":3,"explanation":"정답 근거: have + 목적어 + 원형부정사로, 배관공이 직접 고치는 것이라 원형 fix가 옳다.\n\n보기 비교: ① make는 make me laugh로 고친다. ② let은 Let the kids choose로 고친다. ③ make는 made us run으로 고친다.\n\n기억 연결: make · let · have → O 뒤에 to도 -ing도 없이 원형(laugh · choose · run · fix)."},
  {"n":28,"point":"keep/prevent/stop A from -ing","lesson":"object-form","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["Heavy snow prevented the plane to take off on time.","The fence keeps the deer from entering the garden.","A bad cold stopped her from joining the trip.","The new law discourages companies from dumping waste."],"correctIndex":0,"explanation":"정답 근거: prevent는 A from -ing로 “A가 ~하지 못하게 하다”를 나타낸다. prevented the plane from taking off로 고친다.\n\n보기 비교: ② keep A from -ing라 옳다. ③ stop A from -ing라 옳다. ④ discourage A from -ing도 같은 짝이라 옳다.\n\n기억 연결: prevent · keep · stop · discourage + A + from -ing. “못 하게”가 보이면 from."},
  {"n":29,"point":"감각동사 + 형용사","lesson":"linking","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["The milk smells sour, so please don’t drink it.","The homemade soup tasted deliciously after the hike.","Your idea for the party sounds great to me.","The children looked very tired after the long drive home."],"correctIndex":1,"explanation":"정답 근거: taste는 주어(soup)의 상태를 설명하는 감각동사라 보어에 형용사를 쓴다. tasted delicious로 고친다.\n\n보기 비교: ① smell 뒤에 형용사 sour라 옳다. ③ sound 뒤에 형용사 great라 옳다. ④ look 뒤에 형용사 tired라 옳다.\n\n기억 연결: taste · smell · sound · look · feel → 뒤는 형용사(delicious). -ly를 붙이지 않는다."},
  {"n":30,"point":"감각동사 + 형용사","lesson":"linking","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["The mountain air smells freshly after the rain.","The lake water felt coldly on my bare feet.","The plan sounds reasonably to most of us.","Your new haircut looks great in these photos."],"correctIndex":3,"explanation":"정답 근거: look은 주어(haircut)의 상태를 설명하는 감각동사이고 보어에 형용사 great를 썼으므로 옳다.\n\n보기 비교: ① smell은 smells fresh로 고친다. ② feel은 felt cold로 고친다. ③ sound는 sounds reasonable로 고친다.\n\n기억 연결: smell · feel · sound · look + 형용사. fresh · cold · reasonable · great."},
  {"n":31,"point":"accuse A of B","lesson":"prep-pair","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["The coach accused the referee of favoring the home team.","Critics regard the novel as a modern classic.","She accused her roommate for eating her lunch.","The report blamed the delay on bad weather."],"correctIndex":2,"explanation":"정답 근거: accuse는 비난 · 고발의 이유를 of로 연결한다. accused her roommate of eating her lunch로 고친다. for를 쓰는 짝은 blame A for B다.\n\n보기 비교: ① accuse A of -ing라 옳다. ② regard A as B라 옳다. ④ blame B on A(탓을 ~에게 돌리다)라 옳다.\n\n기억 연결: accuse → of (accuse A of B). blame → for / on. 둘을 섞지 않는다."},
  {"n":32,"point":"think of/regard/refer to A as B","lesson":"prep-pair","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["Most doctors regard sleep as part of good health.","Locals refer the old tower as the Needle.","Many fans think of him as the best goalkeeper ever.","The mayor accused the contractor of wasting money."],"correctIndex":1,"explanation":"정답 근거: refer는 “~을 …라고 부르다”일 때 refer to A as B로 쓴다. to가 빠졌으므로 refer to the old tower as the Needle로 고친다.\n\n보기 비교: ① regard A as B라 옳다. ③ think of A as B라 옳다. ④ accuse A of -ing라 옳다.\n\n기억 연결: refer to A as B · regard A as B · think of A as B → 짝은 as. refer는 to까지 한 덩어리."},
  {"n":33,"point":"think of/regard/refer to A as B","lesson":"prep-pair","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["They think of their dog for a member of the family.","The police accused the man with stealing a bike.","We regard honesty as the most important value.","The staff refer to the old printer for the dinosaur."],"correctIndex":2,"explanation":"정답 근거: regard A as B로 A를 B로 여긴다는 뜻이라 regard honesty as가 옳다.\n\n보기 비교: ① think of A as B이므로 think of their dog as a member로 고친다. ② accuse는 of와 짝이라 accused the man of stealing으로 고친다(with는 charge A with B). ④ refer to A as B이므로 refer to the old printer as the dinosaur로 고친다.\n\n기억 연결: regard · think of · refer to → as. accuse → of. for · with로 바꾸지 않는다."},
  {"n":34,"point":"forget/remember/regret/stop + to vs -ing","lesson":"infinitive-gerund","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["Don’t forget to water the plants while I’m away.","I still remember riding my first bike in the park.","The old man stopped to rest on a quiet bench by the lake.","I regret to tell her the secret at the party last week."],"correctIndex":3,"explanation":"정답 근거: 지난주에 이미 말해 버린 일을 후회하는 것이므로 regret -ing를 써서 regret telling her the secret으로 고친다. regret to do는 “~하게 되어 유감이다”라며 지금 전하는 말에 쓴다.\n\n보기 비교: ① 앞으로 할 일이라 forget to water가 옳다. ② 이미 한 일을 기억하므로 remember riding이 옳다. ③ 쉬려고 멈춘 것이라 목적의 stopped to rest가 옳다.\n\n기억 연결: regret · forget · remember → to는 앞으로 할 일, -ing는 이미 한 일. last week가 보이면 -ing."},
  {"n":35,"point":"forget/remember/regret/stop + to vs -ing","lesson":"infinitive-gerund","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["Remember turning off the gas before you go to bed.","We regret to announce that the flight has been canceled.","She will never forget seeing the ocean for the first time.","My father stopped smoking ten years ago."],"correctIndex":0,"explanation":"정답 근거: 잠자리에 들기 전에 앞으로 할 일을 기억하라는 뜻이므로 Remember to turn off the gas로 고친다.\n\n보기 비교: ② 지금 알리는 소식이 유감이라는 뜻이라 regret to announce가 옳다. ③ 이미 본 경험이라 forget seeing이 옳다. ④ 피우던 담배를 끊었으므로 stopped smoking이 옳다.\n\n기억 연결: remember → before you go(앞으로)면 to, 지난 경험이면 -ing. stop -ing = 그만두다."},
  {"n":36,"point":"forget/remember/regret/stop + to vs -ing","lesson":"infinitive-gerund","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["I’ll never forget to visit Rome with you last spring.","Please remember calling your grandmother tomorrow.","She regrets to quit her job at the bank two years ago.","On the way home, he stopped to pick up some milk."],"correctIndex":3,"explanation":"정답 근거: 집에 오는 길에 우유를 사려고 멈춘 것이므로 목적을 나타내는 stopped to pick up이 옳다.\n\n보기 비교: ① 지난봄에 이미 다녀온 일이므로 forget visiting으로 고친다. ② 내일 할 일이므로 remember to call로 고친다. ③ 2년 전 이미 그만둔 일을 후회하므로 regrets quitting으로 고친다.\n\n기억 연결: stop to do = ~하려고 멈추다 / stop -ing = 그만두다. forget · remember · regret은 시간 표시(last spring · tomorrow)로 판단."},
  {"n":37,"point":"demand/reason/need for","lesson":"finite","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["There is a growing demand for skilled nurses.","The reason of his absence was a family emergency.","The need for clean water is urgent in the region.","It took the crew two days to fix the burst pipe."],"correctIndex":1,"explanation":"정답 근거: 명사 reason은 무엇에 대한 이유인지를 for로 연결한다. The reason for his absence로 고친다.\n\n보기 비교: ① demand for skilled nurses라 옳다. ③ need for clean water라 옳다. ④ It takes + 사람 + 시간 + to부정사라 옳다.\n\n기억 연결: 명사 demand · reason · need → for. reason of(X)."},
  {"n":38,"point":"분사가 본동사 대신 불가","lesson":"finite","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["The man standing by the door is my new neighbor.","Most of the guests invited to the party arrived very late.","The results of the survey being surprising to everyone.","This short novel reads easily in a single evening."],"correctIndex":2,"explanation":"정답 근거: 문장에 본동사가 없다. 분사 being은 서술어가 될 수 없으므로 The results of the survey were surprising to everyone으로 고친다.\n\n보기 비교: ① standing은 man을 꾸미는 분사이고 본동사 is가 따로 있어 옳다. ② invited는 guests를 꾸미고 본동사 arrived가 있어 옳다. ④ read가 능동형으로 “잘 읽힌다”는 뜻의 본동사라 옳다.\n\n기억 연결: being · having이 주어 뒤에서 끝나면 → 본동사 is · are · was · were · has로 바꾼다."},
  {"n":39,"point":"분사가 본동사 대신 불가","lesson":"finite","type":"choice","question":"다음 중 어법상 옳은 것은?","choices":["The students in the back row having trouble hearing.","Every seat in the new theater being very comfortable.","The box sent from Busan arrived early this morning.","The price of the tickets including a free drink."],"correctIndex":2,"explanation":"정답 근거: sent from Busan은 box를 꾸미는 분사구이고, 본동사 arrived가 따로 있으므로 옳다.\n\n보기 비교: ① 본동사가 없으므로 are having trouble 또는 have trouble로 고친다. ② 본동사가 없으므로 is very comfortable로 고친다. ④ 본동사가 없으므로 includes a free drink로 고친다.\n\n기억 연결: 주어가 길어도 본동사 하나는 꼭 필요. having · being · including(-ing)으로 끝나면 문장이 아니다."},
  {"n":40,"point":"It takes (사람) 시간 to do","lesson":"it-takes","type":"choice","question":"다음 중 어법상 옳지 않은 것은?","choices":["It took she almost an hour to find a parking space.","It took us three hours to climb the steep hill.","It takes about a month to learn the basic rules.","It will take the builders a year to finish the tower."],"correctIndex":0,"explanation":"정답 근거: It takes + 사람 + 시간 + to부정사에서 사람은 take의 목적어라 목적격을 쓴다. It took her almost an hour로 고친다.\n\n보기 비교: ② 목적격 us라 옳다. ③ 사람을 생략하고 시간 + to부정사만 쓴 형태라 옳다. ④ the builders가 사람 자리, a year가 시간 자리라 옳다.\n\n기억 연결: It takes + me · us · her(목적격) + 시간 + to do. take 뒤에 she · they(X)."},
  {"n":41,"point":"4형식 불가(introduce/explain/suggest/announce + to)","lesson":"preposition","type":"text","question":"“그 항공사는 승객들에게 출발 지연을 알렸다.”\nThe airline announced the delay ___ the passengers.\n빠진 한 단어를 쓰세요.","answers":["to"],"explanation":"정답 근거: announce는 알리는 내용(the delay)을 목적어로 두고 듣는 사람은 to로 연결하므로 to가 들어간다.\n\n보기 비교: announced the passengers the delay처럼 사람을 먼저 쓰는 4형식은 쓰지 않는다. for나 at도 아니다.\n\n기억 연결: announce · explain · introduce · suggest → 내용 + to + 사람."},
  {"n":42,"point":"타동사에 전치사 금지","lesson":"preposition","type":"text","question":"“그 학생은 종이 울린 뒤 조용히 교실에 들어갔다.”\nThe student quietly ___ the classroom after the bell.\nenter를 과거형으로 쓰고, 전치사가 필요하면 함께 쓰세요.","answers":["entered"],"explanation":"정답 근거: enter는 들어가는 장소를 바로 목적어로 받는 타동사라 전치사 없이 entered 한 단어만 쓴다.\n\n보기 비교: “교실에”라는 한국어 때문에 entered in이나 entered into를 쓰면 틀린다.\n\n기억 연결: enter → 바로 목적어(enter the room). approach · reach · marry · resemble · discuss · answer도 같다."},
  {"n":43,"point":"wait for","lesson":"preposition","type":"text","question":"“우리는 비가 그치기를 30분째 기다리고 있다.”\nWe have been ___ the rain to stop for half an hour.\nwait를 -ing형으로 쓰고, 전치사가 필요하면 함께 쓰세요.","answers":["waiting for"],"explanation":"정답 근거: wait는 목적어를 바로 받지 못하는 자동사라 for가 필요하다. wait for + O + to부정사로 “O가 ~하기를 기다리다”를 나타내므로 waiting for다.\n\n보기 비교: approach · enter처럼 전치사를 빼는 동사와 반대다. waiting the rain(X), waiting to the rain(X).\n\n기억 연결: wait → for가 필수(wait for the rain to stop). “전치사 금지” 무리와 짝으로 외운다."},
  {"n":44,"point":"부가의문문(주절 기준)","lesson":"question-form","type":"text","question":"“그는 네가 그 시험에 합격할 거라고 말했지, 그렇지?”\nHe said that you would pass the exam, ___?\n부가의문문 두 단어를 쓰세요.","answers":["didn't he","didnt he","did he not"],"explanation":"정답 근거: 부가의문문은 주절 He said에 맞춘다. 일반동사 과거 긍정문이므로 didn’t he다.\n\n보기 비교: that절의 you would pass에 맞춘 wouldn’t you는 틀리다.\n\n기억 연결: say · think · believe + that절 → 꼬리는 주절(He said → didn’t he)."},
  {"n":45,"point":"remain + p.p.","lesson":"linking","type":"text","question":"“모든 출입문은 밤새 잠긴 채로 있었다.”\nAll the entrance doors remained ___ throughout the night.\nlock을 알맞은 형태로 바꿔 한 단어로 쓰세요.","answers":["locked"],"explanation":"정답 근거: 문은 잠기는 대상이고 remain 뒤 보어는 주어의 상태를 나타내므로 과거분사 locked를 쓴다.\n\n보기 비교: locking은 문이 무엇을 잠그고 있다는 뜻이 되어 맞지 않고, 원형 lock은 보어 자리에 올 수 없다.\n\n기억 연결: remain + p.p.(remain locked · remain seated · remain closed)."},
  {"n":46,"point":"lie/lay","lesson":"lookalike","type":"text","question":"“그 환자는 아직 침대에 누워 있다.”\nThe patient is still ___ in bed.\nlie 또는 lay 중 알맞은 동사를 -ing형 한 단어로 쓰세요.","answers":["lying"],"explanation":"정답 근거: 눕는 동작에는 목적어가 없으므로 자동사 lie를 쓰고, 그 -ing형은 철자가 바뀌어 lying이다.\n\n보기 비교: laying은 타동사 lay(놓다)의 -ing형이라 목적어가 있어야 한다.\n\n기억 연결: lie → lying(눕다) / lay → laying(놓다). 침대에 “누워 있다”는 lying."},
  {"n":47,"point":"found/find","lesson":"lookalike","type":"text","question":"“그 대학은 1946년에 한 무리의 의사들이 설립했다.”\nThe university was ___ in 1946 by a group of doctors.\nfind 또는 found 중 알맞은 동사를 과거분사 한 단어로 쓰세요.","answers":["founded"],"explanation":"정답 근거: “설립하다”는 found-founded-founded이므로 수동태 was founded다.\n\n보기 비교: was found는 find(찾다)의 수동태라 “발견되었다”라는 다른 뜻이 된다.\n\n기억 연결: 대학 · 회사 · 학교 → found-founded. 잃어버린 물건 → find-found."},
  {"n":48,"point":"rise/raise(수동 불가)","lesson":"no-passive","type":"text","question":"“실업률이 석 달 연속 올랐다.”\nUnemployment [has been risen] for three months in a row.\n대괄호 부분을 두 단어로 고쳐 쓰세요.","answers":["has risen"],"explanation":"정답 근거: rise는 목적어가 없는 자동사라 수동태가 없다. 스스로 오른 것이므로 현재완료 능동 has risen으로 고친다.\n\n보기 비교: 누가 올렸다는 뜻이라면 타동사 raise를 써서 has been raised가 되지만, 실업률은 누가 올리는 대상이 아니다.\n\n기억 연결: rise-rose-risen → be risen(X). 수동이 필요하면 raise → be raised."},
  {"n":49,"point":"간접의문문 어순","lesson":"question-form","type":"text","question":"“나는 그녀가 어디에 사는지 모른다.”\nI don't know where ___.\nshe와 live를 알맞은 어순과 형태로 두 단어로 쓰세요.","answers":["she lives"],"explanation":"정답 근거: where절이 know의 목적어로 들어간 간접의문문이므로 의문사 + 주어 + 동사 어순이다. 주어가 she라 lives다.\n\n보기 비교: where does she live처럼 do를 넣어 도치하지 않는다.\n\n기억 연결: know · wonder · tell + where → “주어 + 동사”(where she lives)."},
  {"n":50,"point":"resist/admit/avoid/deny/mind/postpone + -ing","lesson":"gerund-only","type":"text","question":"“그 꼬마는 병원에 끌려가지 않으려고 버텼다.”\nThe little boy resisted ___ to the doctor.\ntake를 사용해 수동 동명사 두 단어로 쓰세요.","answers":["being taken"],"explanation":"정답 근거: resist는 동명사만 목적어로 쓰고, 꼬마는 데려가지는 쪽이므로 수동 동명사 being + p.p.인 being taken이다.\n\n보기 비교: to be taken은 resist 뒤에 올 수 없고, taking은 꼬마가 누군가를 데려간다는 뜻이 된다.\n\n기억 연결: resist → -ing, 당하면 being p.p.(resist being taken · avoid being seen)."},
  {"n":51,"point":"지각동사/keep/have + p.p.","lesson":"object-voice","type":"text","question":"“비행 중에는 안전벨트를 맨 상태로 두세요.”\nKeep your seat belt ___ during the flight.\nfasten을 알맞은 형태로 바꿔 한 단어로 쓰세요.","answers":["fastened"],"explanation":"정답 근거: 안전벨트는 매어지는 대상이므로 keep + 목적어 + 과거분사 fastened다.\n\n보기 비교: fastening은 벨트가 무엇을 매고 있다는 뜻이 되고, 원형 fasten은 keep의 목적격보어로 쓰지 않는다.\n\n기억 연결: keep + O + p.p.(keep it fastened · keep me posted)."},
  {"n":52,"point":"let + O + be p.p.","lesson":"object-voice","type":"text","question":"“이 사진들이 인터넷에 올라가게 두지 마세요.”\nDon't let these photos ___ online.\npost를 사용해 두 단어로 쓰세요.","answers":["be posted"],"explanation":"정답 근거: let 뒤에는 원형이 오고, 사진은 올려지는 대상이므로 원형 자리에 be + p.p.를 넣어 be posted다.\n\n보기 비교: to be posted는 let 뒤에 to가 붙어 틀리고, posted만 쓰면 let의 원형 자리가 비게 된다.\n\n기억 연결: let + O + be p.p.(let them be posted). want · expect였다면 to be posted."},
  {"n":53,"point":"want/expect + O + to be p.p.","lesson":"object-voice","type":"text","question":"“사장은 그 보고서가 정오까지 마무리되기를 원한다.”\nThe boss wants the report to ___ by noon.\nfinish를 사용해 두 단어로 쓰세요.","answers":["be finished"],"explanation":"정답 근거: want + 목적어 + to부정사에서 보고서는 마무리되는 대상이므로 to 뒤에 be + p.p.를 넣어 be finished다.\n\n보기 비교: to finish는 보고서가 스스로 무엇을 끝낸다는 뜻이 되어 맞지 않다.\n\n기억 연결: want · expect + O + to be p.p.(want it to be finished)."},
  {"n":54,"point":"encourage/allow/advise/cause/force/persuade + O + to","lesson":"object-form","type":"text","question":"“선생님은 우리가 매일 영어 일기를 쓰도록 격려하셨다.”\nOur teacher encouraged us ___ an English diary every day.\nkeep을 알맞은 형태로 바꿔 두 단어로 쓰세요.","answers":["to keep"],"explanation":"정답 근거: encourage는 목적어 뒤에 to부정사를 쓰므로 to keep이다.\n\n보기 비교: keeping이나 원형 keep은 encourage의 목적격보어로 쓰지 않는다.\n\n기억 연결: encourage · allow · advise · cause · force · persuade + O + to do."},
  {"n":55,"point":"make/let/have + 원형","lesson":"object-form","type":"text","question":"“매니저는 우리에게 근무 중 유니폼을 입게 했다.”\nThe manager made us ___ uniforms at work.\nwear를 알맞은 형태로 바꿔 한 단어로 쓰세요.","answers":["wear"],"explanation":"정답 근거: 사역동사 make는 목적어가 직접 하는 동작을 원형부정사로 쓰므로 wear 그대로다.\n\n보기 비교: to wear나 wearing은 make의 목적격보어로 쓰지 않는다(수동태 We were made to wear에서만 to가 살아난다).\n\n기억 연결: make · let · have + O + 원형(made us wear)."},
  {"n":56,"point":"keep/prevent/stop A from -ing","lesson":"object-form","type":"text","question":"“부상 때문에 그녀는 결승전에 뛰지 못했다.”\nAn injury prevented her ___ in the final.\nplay를 사용해 두 단어로 쓰세요.","answers":["from playing"],"explanation":"정답 근거: prevent A from -ing로 “A가 ~하지 못하게 하다”를 나타내므로 from playing이다.\n\n보기 비교: to play는 prevent 뒤 형태가 아니다.\n\n기억 연결: prevent · keep · stop + A + from -ing."},
  {"n":57,"point":"accuse A of B","lesson":"prep-pair","type":"text","question":"“그들은 그 운전자를 빨간불에 달린 혐의로 고발했다.”\nThey accused the driver ___ running a red light.\n빠진 한 단어를 쓰세요.","answers":["of"],"explanation":"정답 근거: accuse A of B로 고발 · 비난의 이유를 of로 연결한다.\n\n보기 비교: for는 blame A for B의 짝이고, with는 charge A with B의 짝이다.\n\n기억 연결: accuse → of(accuse A of -ing)."},
  {"n":58,"point":"forget/remember/regret/stop + to vs -ing","lesson":"infinitive-gerund","type":"text","question":"“내일 아침에 약 먹는 거 잊지 마.”\nDon't forget [taking] your medicine tomorrow morning.\n대괄호 부분을 두 단어로 고쳐 쓰세요.","answers":["to take"],"explanation":"정답 근거: 내일 아침에 앞으로 할 일을 잊지 말라는 뜻이므로 forget to take로 고친다.\n\n보기 비교: forget taking은 이미 먹은 일을 잊는다는 뜻이라 tomorrow와 맞지 않다.\n\n기억 연결: forget · remember + tomorrow(앞으로) → to do / + 지난 일 → -ing."},
  {"n":59,"point":"demand/reason/need for","lesson":"finite","type":"text","question":"“새 병원이 필요하다는 데 모두가 동의했다.”\nEveryone agreed on the need ___ a new hospital.\n빠진 한 단어를 쓰세요.","answers":["for"],"explanation":"정답 근거: 명사 need는 무엇이 필요한지를 for로 연결하므로 the need for a new hospital이다.\n\n보기 비교: the need of나 the need to a new hospital로 쓰지 않는다.\n\n기억 연결: 명사 need · demand · reason → for."},
  {"n":60,"point":"It takes (사람) 시간 to do","lesson":"it-takes","type":"text","question":"“우리가 그 책상을 조립하는 데 두 시간이 걸렸다.”\nIt took ___ two hours to put the desk together.\nwe를 알맞은 형태로 바꿔 한 단어로 쓰세요.","answers":["us"],"explanation":"정답 근거: It takes + 사람 + 시간 + to부정사에서 사람은 take의 목적어이므로 목적격 us를 쓴다.\n\n보기 비교: we나 our는 이 자리에 오지 않는다.\n\n기억 연결: It took + us · her · them + 시간 + to do."}
 ];
 const agreement=['as-well','neither','knowledge','debate-head'];
 // 한 항목 = 한 문제. 위에서 규칙별로 모아 적은 연습 문장은 각각 독립된 문제로 나눈다(예전에는 한 카드가 여러 문장을 돌려 냈다).
 // 규칙의 4지선다(quiz-options.js)가 원래 id를 그대로 쓰고, 여기 적힌 문장은 적힌 순서대로 <id>-v1, <id>-v2 …가 된다.
 // 나뉜 문제는 모두 원래 규칙 정리(title·rule·hook·examples)를 함께 들고 있어 해설 화면이 규칙을 그대로 가르친다.
 // ruleId는 그 문제가 속한 규칙이다. 범위 누락 검사(content-coverage.json)와 개념 묶음(review-policy.js)이 이 값을 기준으로 삼는다.
 const flat={};
 for(const [key,lesson]of Object.entries(bank)){
  const {variants,...rest}=lesson;
  flat[key]={...rest,examples:[...rest.examples],variants:[],ruleId:key};
  variants.forEach((variant,i)=>{flat[key+'-v'+(i+1)]={...rest,examples:[...rest.examples],variants:[variant],ruleId:key};});
 }
 for(const q of DAY1){
  const lesson=DAY1_LESSONS[q.lesson],variant=q.type==='choice'?{type:'choice',question:q.question,choices:q.choices,correctIndex:q.correctIndex,explanation:q.explanation}:{type:'text',question:q.question,answers:q.answers,explanation:q.explanation};
  flat['en-day1-'+String(q.n).padStart(2,'0')]={...lesson,examples:[...lesson.examples],variants:[variant],ruleId:'grammar-verb-'+q.lesson,point:q.point};
 }
 // 문제집에서 옮겨 온 문제는 진도(Day) 단위로 묶고, 그 밖의 문제는 원래 규칙의 분류를 따른다.
 for(const [key,value]of Object.entries(flat))value.topic=key.startsWith('en-day1-')?'Day 1'
  :value.ruleId.startsWith('grammar-agreement-')||agreement.some(k=>value.ruleId===id(k))?'수일치':'영문법';
 root.PRACTICE_BANK=flat;
 if(typeof module!=='undefined'&&module.exports)module.exports=flat;
})(globalThis);
